begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select ok(not has_function_privilege('anon','public.v1_inventory_register_page(text,text,text,text,uuid,integer,integer)','execute'),'Anonymous register denied');
create temporary table page_witness as select gen_random_uuid() id,n from generate_series(1,125) n;
insert into public.v1_inventory_items(id,item_description,unit,minimum_stock,created_by_auth_user_id)
select id,'Page witness '||lpad(n::text,3,'0'),case when n%2=0 then 'Kg' else 'Nos' end,5,'10000000-0000-4000-8000-000000000003' from page_witness;
insert into public.v1_inventory_balances(inventory_item_id,on_hand_qty) select id,case when n<=10 then 2 else 10 end from page_witness;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"10000000-0000-4000-8000-000000000001","role":"authenticated","app_metadata":{"role":"project_engineer"}}',true);
select throws_ok($$select public.v1_inventory_register_page()$$,'42501','V1_INVENTORY_WORKSPACE_DENIED','Project Engineer denied register');
select set_config('request.jwt.claims','{"sub":"10000000-0000-4000-8000-000000000002","role":"authenticated","app_metadata":{"role":"site_engineer"}}',true);
select throws_ok($$select public.v1_inventory_register_page()$$,'42501','V1_INVENTORY_WORKSPACE_DENIED','Site Engineer denied register');
select set_config('request.jwt.claims','{"sub":"10000000-0000-4000-8000-000000000003","role":"authenticated","app_metadata":{"role":"procurement"}}',true);
create temporary table register_pages(page jsonb);
insert into register_pages select public.v1_inventory_register_page(p_search=>'Page witness',p_offset=>offset_value) from (values(0),(50),(100)) offsets(offset_value);
select is((select sum(jsonb_array_length(page->'items'))::integer from register_pages),125,'All three pages retrieve complete stock');
select is((select count(distinct row->>'id')::integer from register_pages,lateral jsonb_array_elements(page->'items') row),125,'Pages have stable nonduplicated item ordering');
select is((public.v1_inventory_register_page(p_search=>'Page witness')->>'total_matches')::integer,125,'Count covers all matches rather than current page');
select is(jsonb_array_length(public.v1_inventory_register_page(p_search=>'Page witness')->'items'),50,'Default page bounded to fifty');
select is((public.v1_inventory_register_page(p_search=>'Page witness',p_offset=>100)->>'has_more')::boolean,false,'Last page has no more records');
select is((public.v1_inventory_register_page(p_search=>'Page witness',p_unit=>'Kg')->>'total_matches')::integer,62,'Unit filtering happens before paging');
select is((public.v1_inventory_register_page(p_search=>'Page witness',p_status=>'low')->>'total_matches')::integer,10,'Low stock filtering uses numeric available quantity');
select is(jsonb_array_length(public.v1_inventory_register_page(p_search=>'Page witness',p_limit=>500)->'items'),125,'Export retrieves beyond the display page');
select is(jsonb_array_length(public.v1_inventory_register_page(p_register=>'reservations')->'items'),0,'Reservation page does not ship the stock catalogue');
select ok(not (public.v1_inventory_register_page()::text ~ 'unit_cost|total_cost|valuation'),'Paged register excludes commercial values');
select set_config('request.jwt.claims','{"sub":"10000000-0000-4000-8000-000000000004","role":"authenticated","app_metadata":{"role":"admin"}}',true);
select lives_ok($$select public.v1_inventory_register_page()$$,'Admin can read register');
select set_config('request.jwt.claims','{"sub":"10000000-0000-4000-8000-000000000009","role":"authenticated","app_metadata":{"role":"senior_mechanical_engineer"}}',true);
select lives_ok($$select public.v1_inventory_register_page()$$,'Senior Mechanical Engineer retains read-only register');
select * from finish();
rollback;
