import 'package:archive/archive.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../domain/accounts_records_models.dart';

class YorksAccountsReportService {
  const YorksAccountsReportService();

  static const xlsxMimeType =
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
  static const pdfMimeType = 'application/pdf';

  Uint8List buildExcel(YorksAccountsReportProjection report) =>
      _AccountsWorkbookWriter.encode({
        _sheetName(report): [
          report.columns,
          for (final row in report.rows)
            [for (final value in row) _safe(value)],
        ],
      });

  Future<Uint8List> buildPdf(YorksAccountsReportProjection report) async {
    final regular = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSans-Regular.ttf'),
    );
    final bold = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSans-Bold.ttf'),
    );
    final arabic = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSansArabic-Regular.ttf'),
    );
    final document = pw.Document(
      title: _title(report),
      author: report.generatedByDisplayName,
      subject: 'Yorks protected Accounts report',
      theme: pw.ThemeData.withFont(
        base: regular,
        bold: bold,
        fontFallback: [arabic],
      ),
    );
    final generated = DateFormat(
      'dd MMM yyyy, HH:mm',
    ).format(report.generatedAt.toLocal());
    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape,
        margin: const pw.EdgeInsets.all(28),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'YORKS AC. & REF.',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#12365E'),
                    fontSize: 11,
                  ),
                ),
                pw.Text(
                  'Commercial access · ${report.accessContext.replaceAll('_', ' ')}',
                  style: const pw.TextStyle(fontSize: 8),
                ),
              ],
            ),
            pw.SizedBox(height: 8),
            pw.Text(
              _title(report),
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            if (report.projectReference != null)
              pw.Text(
                '${report.projectReference} · ${report.projectName ?? ''}',
                style: const pw.TextStyle(fontSize: 9),
              ),
            pw.SizedBox(height: 4),
            pw.Text(
              'Generated by ${report.generatedByDisplayName} · $generated · ${report.currency}',
              style: pw.TextStyle(
                fontSize: 8,
                color: PdfColor.fromHex('#667085'),
              ),
            ),
            pw.SizedBox(height: 10),
          ],
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Protected commercial record',
              style: const pw.TextStyle(fontSize: 7),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 7),
            ),
          ],
        ),
        build: (_) => [
          pw.TableHelper.fromTextArray(
            headers: report.columns,
            data: report.rows,
            headerDecoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#12365E'),
            ),
            headerStyle: pw.TextStyle(
              color: PdfColors.white,
              fontWeight: pw.FontWeight.bold,
              fontSize: 7,
            ),
            cellStyle: const pw.TextStyle(fontSize: 7),
            cellPadding: const pw.EdgeInsets.symmetric(
              horizontal: 4,
              vertical: 5,
            ),
            border: pw.TableBorder.all(
              color: PdfColor.fromHex('#D7E0EB'),
              width: .5,
            ),
          ),
        ],
      ),
    );
    return document.save();
  }

  Future<void> printPdf(YorksAccountsReportProjection report) async {
    final bytes = await buildPdf(report);
    await Printing.layoutPdf(onLayout: (_) async => bytes);
  }

  String excelFileName(YorksAccountsReportProjection report) =>
      '${_fileStem(report)}.xlsx';

  String pdfFileName(YorksAccountsReportProjection report) =>
      '${_fileStem(report)}.pdf';

  static String _title(YorksAccountsReportProjection report) => report
      .reportKind
      .split('_')
      .map(
        (part) => part.isEmpty
            ? part
            : '${part[0].toUpperCase()}${part.substring(1)}',
      )
      .join(' ');

  static String _sheetName(YorksAccountsReportProjection report) {
    final title = _title(report);
    return title.length <= 31 ? title : title.substring(0, 31);
  }

  static String _fileStem(YorksAccountsReportProjection report) {
    final scope = report.projectReference ?? 'Portfolio';
    final stamp = DateFormat('yyyy-MM-dd').format(report.generatedAt.toLocal());
    return 'Yorks_${_token(scope)}_${_token(report.reportKind)}_$stamp';
  }

  static String _token(String value) => value
      .replaceAll(RegExp(r'[^A-Za-z0-9_-]+'), '_')
      .replaceAll(RegExp('_+'), '_')
      .replaceAll(RegExp(r'^_|_$'), '');

  static String _safe(String value) {
    final normalized = value.replaceAll('\u0000', '');
    return RegExp(r'^[=+\-@]').hasMatch(normalized)
        ? "'$normalized"
        : normalized;
  }
}

class _AccountsWorkbookWriter {
  static Uint8List encode(Map<String, List<List<String>>> sheets) {
    final names = sheets.keys.toList(growable: false);
    final archive = Archive()
      ..addFile(
        ArchiveFile.string('[Content_Types].xml', _contentTypes(names.length)),
      )
      ..addFile(ArchiveFile.string('_rels/.rels', _rootRels))
      ..addFile(ArchiveFile.string('xl/workbook.xml', _workbook(names)))
      ..addFile(
        ArchiveFile.string(
          'xl/_rels/workbook.xml.rels',
          _workbookRels(names.length),
        ),
      )
      ..addFile(ArchiveFile.string('xl/styles.xml', _styles));
    for (var index = 0; index < names.length; index++) {
      archive.addFile(
        ArchiveFile.string(
          'xl/worksheets/sheet${index + 1}.xml',
          _sheet(sheets[names[index]]!),
        ),
      );
    }
    return Uint8List.fromList(ZipEncoder().encode(archive));
  }

  static String _sheet(List<List<String>> rows) {
    final maxColumns = rows.fold<int>(
      1,
      (maximum, row) => row.length > maximum ? row.length : maximum,
    );
    final out = StringBuffer(
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
      '<sheetViews><sheetView workbookViewId="0"><pane ySplit="1" '
      'topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView>'
      '</sheetViews><sheetData>',
    );
    for (var rowIndex = 0; rowIndex < rows.length; rowIndex++) {
      out.write('<row r="${rowIndex + 1}">');
      for (
        var columnIndex = 0;
        columnIndex < rows[rowIndex].length;
        columnIndex++
      ) {
        out.write(
          '<c r="${_column(columnIndex)}${rowIndex + 1}" '
          's="${rowIndex == 0 ? 1 : 2}" t="inlineStr"><is><t '
          'xml:space="preserve">${_xml(rows[rowIndex][columnIndex])}'
          '</t></is></c>',
        );
      }
      out.write('</row>');
    }
    out.write(
      '</sheetData><autoFilter ref="A1:${_column(maxColumns - 1)}'
      '${rows.isEmpty ? 1 : rows.length}"/></worksheet>',
    );
    return out.toString();
  }

  static String _contentTypes(int count) =>
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
      '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
      '<Default Extension="xml" ContentType="application/xml"/>'
      '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
      '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
      '${[for (var i = 1; i <= count; i++) '<Override PartName="/xl/worksheets/sheet$i.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'].join()}'
      '</Types>';

  static const _rootRels =
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
      '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
      '</Relationships>';

  static String _workbook(List<String> names) =>
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
      'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
      '<sheets>${[for (var i = 0; i < names.length; i++) '<sheet name="${_xml(names[i])}" sheetId="${i + 1}" r:id="rId${i + 1}"/>'].join()}</sheets>'
      '</workbook>';

  static String _workbookRels(int count) =>
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
      '${[for (var i = 1; i <= count; i++) '<Relationship Id="rId$i" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet$i.xml"/>'].join()}'
      '<Relationship Id="rId${count + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
      '</Relationships>';

  static const _styles =
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
      '<fonts count="2"><font><sz val="11"/><name val="Aptos"/></font>'
      '<font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Aptos"/></font></fonts>'
      '<fills count="3"><fill><patternFill patternType="none"/></fill>'
      '<fill><patternFill patternType="gray125"/></fill>'
      '<fill><patternFill patternType="solid"><fgColor rgb="FF12365F"/></patternFill></fill></fills>'
      '<borders count="2"><border/><border><left style="thin"><color rgb="FFD7E0EB"/></left>'
      '<right style="thin"><color rgb="FFD7E0EB"/></right><top style="thin"><color rgb="FFD7E0EB"/></top>'
      '<bottom style="thin"><color rgb="FFD7E0EB"/></bottom></border></borders>'
      '<cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="3"><xf/>'
      '<xf fontId="1" fillId="2" borderId="1" applyFont="1" applyFill="1" applyBorder="1"/>'
      '<xf borderId="1" applyBorder="1"/></cellXfs></styleSheet>';

  static String _column(int index) {
    var value = index + 1;
    var result = '';
    while (value > 0) {
      value--;
      result = String.fromCharCode(65 + value % 26) + result;
      value ~/= 26;
    }
    return result;
  }

  static String _xml(String value) => value
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;');
}
