// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs5vRHMyZXegfAQa-us3FyiCvhJVBQm7A',
    appId: '1:1003807035272:web:206e34aee93941c68ff43d',
    messagingSenderId: '1003807035272',
    projectId: 'yorks-48c40',
    authDomain: 'yorks-48c40.firebaseapp.com',
    storageBucket: 'yorks-48c40.firebasestorage.app',
    measurementId: 'G-KCVG46BZL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1GEVL2wNXgdBed7ZdA-xhWhzILxnsXNc',
    appId: '1:1003807035272:android:864f0fd2be15881c8ff43d',
    messagingSenderId: '1003807035272',
    projectId: 'yorks-48c40',
    storageBucket: 'yorks-48c40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeBkuJ6uLuzX-239wwvvaReIESylg7wWM',
    appId: '1:1003807035272:ios:96b3bd51e9c5c44b8ff43d',
    messagingSenderId: '1003807035272',
    projectId: 'yorks-48c40',
    storageBucket: 'yorks-48c40.firebasestorage.app',
    iosBundleId: 'com.yorks.app',
  );
}
