"""Generate module notification copy for Dart and Edge from one reviewed source."""
import argparse
import ast
import difflib
import json
import re
import subprocess
import tempfile
from pathlib import Path
from notification_producer_inventory import validate_coverage
root=Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true', help='Fail if generated files are stale; do not modify them')
args = parser.parse_args()
rows=json.loads((root/'contracts/notifications/module_events.v1.json').read_text())
workflow_rows=json.loads((root/'contracts/notifications/workflow_events.v1.json').read_text())
if set(rows) & set(workflow_rows):
 raise SystemExit('Module and workflow catalogue event codes must be disjoint')
for code, row in {**rows, **workflow_rows}.items():
 for field in ('title', 'body'):
  if set(row[field]) != {'en', 'ar', 'ur', 'hi'} or any(not text.strip() for text in row[field].values()):
   raise SystemExit(f'Incomplete notification localization: {code}.{field}')
 if code != '_fallback' and any(row['title'][language] == workflow_rows['_fallback']['title'][language]
   for language in ('en', 'ar', 'ur', 'hi')):
  raise SystemExit(f'Known notification event needs a meaningful title: {code}')
validate_coverage(root, {**rows, **workflow_rows})

# Retain the existing Dart workflow-copy API during this rollout, but enforce
# exact source parity so OS alerts cannot drift from the four in-app languages.
dart_model = (root/'lib/shared/models/yorks_v1_notification.dart').read_text()
def workflow_copy(block):
 result = {'title': {}, 'body': {}}
 for label, language in [('english', 'en'), ('arabic', 'ar'), ('urdu', 'ur'), ('hindi', 'hi')]:
  for field in ('Title', 'Body'):
   match = re.search(label+field+r":\s*('(?:[^'\\]|\\.)*')", block)
   if not match:
    raise SystemExit(f'Cannot verify Dart workflow copy: {label}{field}')
   result[field.lower()][language] = ast.literal_eval(match[1])
 return result
constants = {match[1]: workflow_copy(match[2]) for match in re.finditer(
 r'const (_\w+) = YorksV1NotificationCopy\((.*?)\n\);', dart_model, re.S)}
dart_workflow = {}
for match in re.finditer(r"  '([^']+)': (?:YorksV1NotificationCopy\((.*?)\n  \),|(_\w+),)",
 dart_model[dart_model.index('const _eventCopy'):], re.S):
 dart_workflow[match[1]] = workflow_copy(match[2]) if match[2] else constants[match[3]]
dart_workflow['_fallback'] = constants['_workflowUpdate']
if set(dart_workflow) != set(workflow_rows):
 raise SystemExit('Dart and shared workflow catalogue event codes differ')
for code, copy in dart_workflow.items():
 for field in ('title', 'body'):
  if copy[field] != workflow_rows[code][field]:
   raise SystemExit(f'Dart and shared workflow copy differ: {code}.{field}')
# JSON strings are valid Dart double-quoted strings with dollar signs escaped.
def dart(value): return json.dumps(value,ensure_ascii=False).replace('$','\\$')
lines=["// Generated by tool/generate-notification-catalogue.py. Do not edit.","import 'app_language.dart';","const notificationModuleEvents = <String, Map<String, Object>>{"]
for code,row in rows.items():
 lines.append(f'  {dart(code)}: {{')
 for field in ('title','body'):
  lines.append(f'    {dart(field)}: <String>[{", ".join(dart(row[field][l]) for l in ["en","ar","ur","hi"])}],')
 lines.append(f'    "destination": {dart(row["destination"])}, "urgent": {str(row["urgent"]).lower()},')
 lines.append('  },')
lines+=['};', '''String moduleNotificationText(String code, String field, AppLanguage language) {
  final values = notificationModuleEvents[code]![field] as List<String>;
  final index = switch(language) { AppLanguage.english => 0, AppLanguage.arabic => 1, AppLanguage.urdu => 2, AppLanguage.hindi => 3 };
  return values[index];
}''']
dart_source='\n'.join(lines)+'\n'
# Match the repository formatter without mutating tracked files in check mode.
with tempfile.TemporaryDirectory() as directory:
 path=Path(directory)/'catalogue.dart'
 path.write_text(dart_source)
 subprocess.run(['dart','format',str(path)],check=True,capture_output=True)
 dart_source=path.read_text()
outputs={'lib/shared/models/notification_module_catalogue.dart': dart_source}
outputs['supabase/functions/send-push/module_catalogue.ts'] = ('// Generated by tool/generate-notification-catalogue.py. Do not edit.\nexport const moduleEvents: Record<string, {title: Record<string,string>; body: Record<string,string>; destination: string; urgent: boolean}> = '+json.dumps(rows,ensure_ascii=False,indent=2)+';\n'
 + 'export const workflowEvents: Record<string, {title: Record<string,string>; body: Record<string,string>; type: "request" | "project" | "info"}> = '+json.dumps(workflow_rows,ensure_ascii=False,indent=2)+';\n')

failed = False
for name, source in outputs.items():
 path = root/name
 if args.check:
  current = path.read_text() if path.exists() else ''
  if current != source:
   failed = True
   print(''.join(difflib.unified_diff(current.splitlines(True), source.splitlines(True), fromfile=name, tofile='generated')), end='')
 else:
  path.write_text(source)
if failed:
 raise SystemExit('Notification catalogue is stale. Run python3 tool/generate-notification-catalogue.py')
print('Notification catalogue verified' if args.check else 'Notification catalogue generated')
