"""Generate module notification copy for Dart and Edge from one reviewed source."""
import json
from pathlib import Path
root=Path(__file__).resolve().parent.parent
rows=json.loads((root/'contracts/notifications/module_events.v1.json').read_text())
# JSON strings are valid Dart double-quoted strings with dollar signs escaped.
def dart(value): return json.dumps(value,ensure_ascii=False).replace('$','\\$')
lines=["// Generated by tool/generate-notification-catalogue.py. Do not edit.","import 'app_language.dart';","const notificationModuleEvents = <String, Map<String, Object>>{"]
for code,row in rows.items():
 lines.append(f'  {dart(code)}: {{')
 for field in ('title','body'):
  lines.append(f'    {dart(field)}: <String>[{", ".join(dart(row[field][l]) for l in ["en","ar","ur","hi"])}],')
 lines.append(f'    "destination": {dart(row["destination"])}, "urgent": {str(row["urgent"]).lower()},')
 lines.append('  },')
lines+=['};', '''String moduleNotificationText(String code, String field, AppLanguage language) {
  final values = notificationModuleEvents[code]![field] as List<String>;
  final index = switch(language) { AppLanguage.english => 0, AppLanguage.arabic => 1, AppLanguage.urdu => 2, AppLanguage.hindi => 3 };
  return values[index];
}''']
(root/'lib/shared/models/notification_module_catalogue.dart').write_text('\n'.join(lines)+'\n')
(root/'supabase/functions/send-push/module_catalogue.ts').write_text('// Generated by tool/generate-notification-catalogue.py. Do not edit.\nexport const moduleEvents: Record<string, {title: Record<string,string>; body: Record<string,string>; destination: string; urgent: boolean}> = '+json.dumps(rows,ensure_ascii=False,indent=2)+';\n')
