// Generated by tool/generate-notification-catalogue.py. Do not edit.
import 'app_language.dart';

const notificationModuleEvents = <String, Map<String, Object>>{
  "accounts_claim_ready": {
    "title": <String>[
      "Claim ready for Accounts",
      "المطالبة جاهزة للحسابات",
      "اکاؤنٹس کے لیے کلیم تیار",
      "लेखा के लिए दावा तैयार",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "invoices",
    "urgent": false,
  },
  "accounts_claim_returned": {
    "title": <String>[
      "Claim changes required",
      "مطلوب تعديل المطالبة",
      "کلیم میں تبدیلی درکار",
      "दावे में बदलाव आवश्यक",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "invoices",
    "urgent": false,
  },
  "accounts_certification_difference": {
    "title": <String>[
      "Certification needs review",
      "شهادة الدفع تحتاج مراجعة",
      "سرٹیفیکیشن کا جائزہ درکار",
      "प्रमाणन की समीक्षा आवश्यक",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "invoices",
    "urgent": false,
  },
  "accounts_supplier_evidence_incomplete": {
    "title": <String>[
      "Supplier bill evidence incomplete",
      "مستندات فاتورة المورد غير مكتملة",
      "سپلائر بل کے ثبوت نامکمل",
      "आपूर्तिकर्ता बिल के प्रमाण अधूरे",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "supplier-bills",
    "urgent": false,
  },
  "accounts_supplier_bill_ready": {
    "title": <String>[
      "Supplier bill ready for Accounts",
      "فاتورة المورد جاهزة للحسابات",
      "سپلائر بل اکاؤنٹس کے لیے تیار",
      "आपूर्तिकर्ता बिल लेखा के लिए तैयार",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "supplier-bills",
    "urgent": false,
  },
  "accounts_invoice_due_soon": {
    "title": <String>[
      "Invoice due soon",
      "موعد الفاتورة قريب",
      "انوائس جلد واجب الادا",
      "चालान जल्द देय",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "invoices",
    "urgent": false,
  },
  "accounts_invoice_overdue": {
    "title": <String>[
      "Invoice overdue",
      "فاتورة متأخرة",
      "انوائس کی تاریخ گزر گئی",
      "चालान अतिदेय",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "invoices",
    "urgent": true,
  },
  "accounts_pdc_due_soon": {
    "title": <String>[
      "Cheque due soon",
      "موعد الشيك قريب",
      "چیک جلد واجب الادا",
      "चेक जल्द देय",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "receipts-pdc",
    "urgent": false,
  },
  "accounts_pdc_overdue": {
    "title": <String>[
      "Cheque overdue",
      "شيك متأخر",
      "چیک کی تاریخ گزر گئی",
      "चेक अतिदेय",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "receipts-pdc",
    "urgent": true,
  },
  "workforce_period_submitted": {
    "title": <String>[
      "Timesheet ready for review",
      "كشف الدوام جاهز للمراجعة",
      "ٹائم شیٹ جائزے کے لیے تیار",
      "टाइमशीट समीक्षा के लिए तैयार",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_period_returned": {
    "title": <String>[
      "Timesheet changes required",
      "مطلوب تعديل كشف الدوام",
      "ٹائم شیٹ میں تبدیلی درکار",
      "टाइमशीट में बदलाव आवश्यक",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_correction_completed": {
    "title": <String>[
      "Timesheet corrected",
      "تم تصحيح كشف الدوام",
      "ٹائم شیٹ درست کر دی گئی",
      "टाइमशीट सुधारी गई",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_period_verified": {
    "title": <String>[
      "Timesheet verified",
      "تم التحقق من كشف الدوام",
      "ٹائم شیٹ کی تصدیق ہو گئی",
      "टाइमशीट सत्यापित",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_period_approved_locked": {
    "title": <String>[
      "Timesheet approved and locked",
      "تم اعتماد وإقفال كشف الدوام",
      "ٹائم شیٹ منظور اور مقفل",
      "टाइमशीट स्वीकृत और लॉक",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_reopen_requested": {
    "title": <String>[
      "Timesheet reopening requested",
      "طُلب إعادة فتح كشف الدوام",
      "ٹائم شیٹ دوبارہ کھولنے کی درخواست",
      "टाइमशीट दोबारा खोलने का अनुरोध",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_reopen_approved": {
    "title": <String>[
      "Timesheet reopening approved",
      "اعتُمد إعادة فتح كشف الدوام",
      "ٹائم شیٹ دوبارہ کھولنے کی منظوری",
      "टाइमशीट दोबारा खोलना स्वीकृत",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_final_approval_required": {
    "title": <String>[
      "Timesheet final approval required",
      "مطلوب الاعتماد النهائي لكشف الدوام",
      "ٹائم شیٹ کی حتمی منظوری درکار",
      "टाइमशीट की अंतिम स्वीकृति आवश्यक",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_daily_attendance_missing": {
    "title": <String>[
      "Daily attendance missing",
      "الحضور اليومي غير مسجل",
      "روزانہ حاضری درج نہیں",
      "दैनिक उपस्थिति अनुपलब्ध",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "attendance",
    "urgent": false,
  },
  "workforce_monthly_period_incomplete": {
    "title": <String>[
      "Monthly timesheet incomplete",
      "كشف الدوام الشهري غير مكتمل",
      "ماہانہ ٹائم شیٹ نامکمل",
      "मासिक टाइमशीट अधूरी",
    ],
    "body": <String>[
      "Open the workspace to review this update.",
      "افتح مساحة العمل لمراجعة هذا التحديث.",
      "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
};
String moduleNotificationText(String code, String field, AppLanguage language) {
  final values = notificationModuleEvents[code]![field] as List<String>;
  final index = switch (language) {
    AppLanguage.english => 0,
    AppLanguage.arabic => 1,
    AppLanguage.urdu => 2,
    AppLanguage.hindi => 3,
  };
  return values[index];
}
