// Generated by tool/generate-notification-catalogue.py. Do not edit.
import 'app_language.dart';

const notificationModuleEvents = <String, Map<String, Object>>{
  "accounts_claim_ready": {
    "title": <String>[
      "Claim ready for Accounts",
      "المطالبة جاهزة للحسابات",
      "اکاؤنٹس کے لیے کلیم تیار",
      "लेखा के लिए दावा तैयार",
    ],
    "body": <String>[
      "Review the claim before preparing its invoice.",
      "راجع المطالبة قبل إعداد فاتورتها.",
      "انوائس تیار کرنے سے پہلے کلیم کا جائزہ لیں۔",
      "चालान बनाने से पहले दावे की समीक्षा करें।",
    ],
    "destination": "invoices",
    "urgent": false,
  },
  "accounts_claim_returned": {
    "title": <String>[
      "Claim changes required",
      "مطلوب تعديل المطالبة",
      "کلیم میں تبدیلی درکار",
      "दावे में बदलाव आवश्यक",
    ],
    "body": <String>[
      "Review the returned invoice and the reason for changes.",
      "راجع الفاتورة المعادة وسبب التعديلات المطلوبة.",
      "واپس کی گئی انوائس اور تبدیلیوں کی وجہ کا جائزہ لیں۔",
      "लौटाए गए चालान और बदलाव के कारण की समीक्षा करें।",
    ],
    "destination": "invoices",
    "urgent": false,
  },
  "accounts_certification_difference": {
    "title": <String>[
      "Certification needs review",
      "شهادة الدفع تحتاج مراجعة",
      "سرٹیفیکیشن کا جائزہ درکار",
      "प्रमाणन की समीक्षा आवश्यक",
    ],
    "body": <String>[
      "Review the recorded certification difference and its reason.",
      "راجع الفرق المسجل في شهادة الدفع وسببه.",
      "سرٹیفیکیشن میں درج فرق اور اس کی وجہ کا جائزہ لیں۔",
      "दर्ज प्रमाणन अंतर और उसके कारण की समीक्षा करें।",
    ],
    "destination": "invoices",
    "urgent": false,
  },
  "accounts_supplier_evidence_incomplete": {
    "title": <String>[
      "Supplier bill evidence incomplete",
      "مستندات فاتورة المورد غير مكتملة",
      "سپلائر بل کے ثبوت نامکمل",
      "आपूर्तिकर्ता बिल के प्रमाण अधूरे",
    ],
    "body": <String>[
      "Review the supplier bill and add the missing matching evidence.",
      "راجع فاتورة المورد وأضف مستندات المطابقة الناقصة.",
      "سپلائر بل کا جائزہ لیں اور مطابقت کے نامکمل ثبوت شامل کریں۔",
      "आपूर्तिकर्ता बिल की समीक्षा करें और मिलान के अधूरे प्रमाण जोड़ें।",
    ],
    "destination": "supplier-bills",
    "urgent": false,
  },
  "accounts_supplier_bill_ready": {
    "title": <String>[
      "Supplier bill ready for Accounts",
      "فاتورة المورد جاهزة للحسابات",
      "سپلائر بل اکاؤنٹس کے لیے تیار",
      "आपूर्तिकर्ता बिल लेखा के लिए तैयार",
    ],
    "body": <String>[
      "Review the matched supplier bill before approving payment.",
      "راجع فاتورة المورد المطابقة قبل اعتماد الدفع.",
      "ادائیگی منظور کرنے سے پہلے میچ شدہ سپلائر بل کا جائزہ لیں۔",
      "भुगतान स्वीकृत करने से पहले मिलान किए गए आपूर्तिकर्ता बिल की समीक्षा करें।",
    ],
    "destination": "supplier-bills",
    "urgent": false,
  },
  "accounts_invoice_due_soon": {
    "title": <String>[
      "Invoice due soon",
      "موعد الفاتورة قريب",
      "انوائس جلد واجب الادا",
      "चालान जल्द देय",
    ],
    "body": <String>[
      "Review the invoice due date and recorded receipts.",
      "راجع تاريخ استحقاق الفاتورة والمقبوضات المسجلة.",
      "انوائس کی مقررہ تاریخ اور درج وصولیوں کا جائزہ لیں۔",
      "चालान की देय तिथि और दर्ज प्राप्तियों की समीक्षा करें।",
    ],
    "destination": "invoices",
    "urgent": false,
  },
  "accounts_invoice_overdue": {
    "title": <String>[
      "Invoice overdue",
      "فاتورة متأخرة",
      "انوائس کی تاریخ گزر گئی",
      "चालान अतिदेय",
    ],
    "body": <String>[
      "Review the overdue invoice and update receipts when payment arrives.",
      "راجع الفاتورة المتأخرة وحدّث المقبوضات عند استلام الدفع.",
      "تاخیر شدہ انوائس کا جائزہ لیں اور ادائیگی موصول ہونے پر وصولیاں اپ ڈیٹ کریں۔",
      "अतिदेय चालान की समीक्षा करें और भुगतान आने पर प्राप्तियां अपडेट करें।",
    ],
    "destination": "invoices",
    "urgent": true,
  },
  "accounts_pdc_due_soon": {
    "title": <String>[
      "Cheque due soon",
      "موعد الشيك قريب",
      "چیک جلد واجب الادا",
      "चेक जल्द देय",
    ],
    "body": <String>[
      "Review the cheque date and next collection step.",
      "راجع تاريخ الشيك وخطوة التحصيل التالية.",
      "چیک کی تاریخ اور اگلے وصولی مرحلے کا جائزہ لیں۔",
      "चेक की तिथि और अगले संग्रह चरण की समीक्षा करें।",
    ],
    "destination": "receipts-pdc",
    "urgent": false,
  },
  "accounts_pdc_overdue": {
    "title": <String>[
      "Cheque overdue",
      "شيك متأخر",
      "چیک کی تاریخ گزر گئی",
      "चेक अतिदेय",
    ],
    "body": <String>[
      "Review the overdue cheque and record its current status.",
      "راجع الشيك المتأخر وسجل حالته الحالية.",
      "تاخیر شدہ چیک کا جائزہ لیں اور اس کی موجودہ حالت درج کریں۔",
      "अतिदेय चेक की समीक्षा करें और उसकी वर्तमान स्थिति दर्ज करें।",
    ],
    "destination": "receipts-pdc",
    "urgent": true,
  },
  "workforce_period_submitted": {
    "title": <String>[
      "Timesheet ready for review",
      "كشف الدوام جاهز للمراجعة",
      "ٹائم شیٹ جائزے کے لیے تیار",
      "टाइमशीट समीक्षा के लिए तैयार",
    ],
    "body": <String>[
      "Review the submitted monthly timesheet.",
      "راجع كشف الدوام الشهري المقدم.",
      "جمع کردہ ماہانہ ٹائم شیٹ کا جائزہ لیں۔",
      "जमा की गई मासिक टाइमशीट की समीक्षा करें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_period_returned": {
    "title": <String>[
      "Timesheet changes required",
      "مطلوب تعديل كشف الدوام",
      "ٹائم شیٹ میں تبدیلی درکار",
      "टाइमशीट में बदलाव आवश्यक",
    ],
    "body": <String>[
      "Review the return reason and correct the monthly timesheet.",
      "راجع سبب الإعادة وصحح كشف الدوام الشهري.",
      "واپسی کی وجہ دیکھیں اور ماہانہ ٹائم شیٹ درست کریں۔",
      "लौटाने का कारण देखें और मासिक टाइमशीट सुधारें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_correction_completed": {
    "title": <String>[
      "Timesheet corrected",
      "تم تصحيح كشف الدوام",
      "ٹائم شیٹ درست کر دی گئی",
      "टाइमशीट सुधारी गई",
    ],
    "body": <String>[
      "Review the corrections recorded in the monthly timesheet.",
      "راجع التصحيحات المسجلة في كشف الدوام الشهري.",
      "ماہانہ ٹائم شیٹ میں درج تصحیحات کا جائزہ لیں۔",
      "मासिक टाइमशीट में दर्ज सुधारों की समीक्षा करें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_period_verified": {
    "title": <String>[
      "Timesheet verified",
      "تم التحقق من كشف الدوام",
      "ٹائم شیٹ کی تصدیق ہو گئی",
      "टाइमशीट सत्यापित",
    ],
    "body": <String>[
      "The monthly timesheet was verified and is awaiting final approval.",
      "تم التحقق من كشف الدوام الشهري وهو بانتظار الاعتماد النهائي.",
      "ماہانہ ٹائم شیٹ کی تصدیق ہو گئی اور حتمی منظوری کا انتظار ہے۔",
      "मासिक टाइमशीट सत्यापित हुई और अंतिम स्वीकृति की प्रतीक्षा में है।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_period_approved_locked": {
    "title": <String>[
      "Timesheet approved and locked",
      "تم اعتماد وإقفال كشف الدوام",
      "ٹائم شیٹ منظور اور مقفل",
      "टाइमशीट स्वीकृत और लॉक",
    ],
    "body": <String>[
      "Open the approved monthly timesheet to review its locked record.",
      "افتح كشف الدوام الشهري المعتمد لمراجعة سجله المقفل.",
      "مقفل ریکارڈ دیکھنے کے لیے منظور شدہ ماہانہ ٹائم شیٹ کھولیں۔",
      "लॉक किए गए रिकॉर्ड की समीक्षा के लिए स्वीकृत मासिक टाइमशीट खोलें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_reopen_requested": {
    "title": <String>[
      "Timesheet reopening requested",
      "طُلب إعادة فتح كشف الدوام",
      "ٹائم شیٹ دوبارہ کھولنے کی درخواست",
      "टाइमशीट दोबारा खोलने का अनुरोध",
    ],
    "body": <String>[
      "Review the request and reason to reopen the locked timesheet.",
      "راجع طلب إعادة فتح كشف الدوام المقفل وسببه.",
      "مقفل ٹائم شیٹ دوبارہ کھولنے کی درخواست اور وجہ کا جائزہ لیں۔",
      "लॉक टाइमशीट दोबारा खोलने के अनुरोध और कारण की समीक्षा करें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_reopen_approved": {
    "title": <String>[
      "Timesheet reopening approved",
      "اعتُمد إعادة فتح كشف الدوام",
      "ٹائم شیٹ دوبارہ کھولنے کی منظوری",
      "टाइमशीट दोबारा खोलना स्वीकृत",
    ],
    "body": <String>[
      "Open the reopened monthly timesheet to make the permitted corrections.",
      "افتح كشف الدوام الشهري المعاد فتحه لإجراء التصحيحات المسموح بها.",
      "اجازت یافتہ تصحیحات کے لیے دوبارہ کھولی گئی ماہانہ ٹائم شیٹ کھولیں۔",
      "अनुमत सुधारों के लिए दोबारा खोली गई मासिक टाइमशीट खोलें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_final_approval_required": {
    "title": <String>[
      "Timesheet final approval required",
      "مطلوب الاعتماد النهائي لكشف الدوام",
      "ٹائم شیٹ کی حتمی منظوری درکار",
      "टाइमशीट की अंतिम स्वीकृति आवश्यक",
    ],
    "body": <String>[
      "Review the verified monthly timesheet for final approval.",
      "راجع كشف الدوام الشهري الذي تم التحقق منه للاعتماد النهائي.",
      "حتمی منظوری کے لیے تصدیق شدہ ماہانہ ٹائم شیٹ کا جائزہ لیں۔",
      "अंतिम स्वीकृति के लिए सत्यापित मासिक टाइमशीट की समीक्षा करें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
  "workforce_daily_attendance_missing": {
    "title": <String>[
      "Daily attendance missing",
      "الحضور اليومي غير مسجل",
      "روزانہ حاضری درج نہیں",
      "दैनिक उपस्थिति अनुपलब्ध",
    ],
    "body": <String>[
      "Review missing attendance in your assigned team.",
      "راجع الحضور غير المسجل في الفريق المسند إليك.",
      "آپ کی تفویض کردہ ٹیم میں نامکمل حاضری کا جائزہ لیں۔",
      "अपनी नियुक्त टीम में अनुपलब्ध उपस्थिति की समीक्षा करें।",
    ],
    "destination": "attendance",
    "urgent": false,
  },
  "workforce_monthly_period_incomplete": {
    "title": <String>[
      "Monthly timesheet incomplete",
      "كشف الدوام الشهري غير مكتمل",
      "ماہانہ ٹائم شیٹ نامکمل",
      "मासिक टाइमशीट अधूरी",
    ],
    "body": <String>[
      "Complete missing attendance before submitting the monthly timesheet.",
      "أكمل الحضور غير المسجل قبل تقديم كشف الدوام الشهري.",
      "ماہانہ ٹائم شیٹ جمع کرنے سے پہلے نامکمل حاضری مکمل کریں۔",
      "मासिक टाइमशीट जमा करने से पहले अनुपलब्ध उपस्थिति पूरी करें।",
    ],
    "destination": "timesheets",
    "urgent": false,
  },
};
String moduleNotificationText(String code, String field, AppLanguage language) {
  final values = notificationModuleEvents[code]![field] as List<String>;
  final index = switch (language) {
    AppLanguage.english => 0,
    AppLanguage.arabic => 1,
    AppLanguage.urdu => 2,
    AppLanguage.hindi => 3,
  };
  return values[index];
}
