import 'app_language.dart';
import 'yorks_v1_permission_management.dart';
import 'yorks_v1_role.dart';

/// Centralized copy for the protected scoped-permission workspace.
///
/// Capability keys are server-owned. Known modules/actions receive polished
/// translations; a future catalogue entry falls back to a readable label
/// without making the client reject the otherwise valid server projection.
abstract final class YorksV1PermissionStrings {
  static String text(AppLanguage language, String key, {String? fallback}) =>
      _localized[language.code]?[key] ??
      _english[key] ??
      fallback ??
      _readable(key);

  static String module(AppLanguage language, String module) =>
      text(language, 'module.$module', fallback: _readable(module));

  static String action(AppLanguage language, String action) =>
      text(language, 'action.$action', fallback: _readable(action));

  static String role(AppLanguage language, YorksV1Role? role) => role == null
      ? text(language, 'unassigned')
      : text(
          language,
          'role.${role.claimValue}',
          fallback: _readable(role.claimValue),
        );

  static String effect(
    AppLanguage language,
    YorksV1PermissionAssignmentEffect effect,
  ) => text(language, 'effect.${effect.wireValue}');

  static String source(
    AppLanguage language,
    YorksV1PermissionEffectiveSource source,
  ) => text(language, 'source.${source.wireValue}');

  static String risk(AppLanguage language, YorksV1PermissionRiskLevel risk) =>
      text(language, 'risk.${risk.wireValue}');

  static String scope(AppLanguage language, YorksV1PermissionScopeKind scope) =>
      text(language, 'scope.${scope.wireValue}');

  static String historyKind(
    AppLanguage language,
    YorksV1PermissionHistoryEventKind kind,
  ) => text(language, 'history.${kind.wireValue}');

  static String _readable(String raw) {
    final words = raw
        .replaceAll('.', ' ')
        .replaceAll('_', ' ')
        .trim()
        .split(RegExp(r'\s+'))
        .where((word) => word.isNotEmpty)
        .toList(growable: false);
    if (words.isEmpty) return raw;
    return words
        .map((word) => '${word[0].toUpperCase()}${word.substring(1)}')
        .join(' ');
  }

  static const Map<String, String> _english = {
    'eyebrow': 'ADMINISTRATION',
    'title': 'Scoped Access',
    'subtitle':
        'Review effective access, its source and project scope before making an audited change.',
    'back_to_users': 'Back to User Management',
    'search_permissions': 'Search permissions',
    'search_hint': 'Find a module or action…',
    'all_modules': 'All modules',
    'effective_access': 'Effective access',
    'role_baseline': 'Role baseline',
    'custom_assignments': 'Custom assignments',
    'project_scope': 'Project scope',
    'permission_history': 'Permission history',
    'permissions': 'Permissions',
    'overview': 'Access overview',
    'active': 'Active',
    'deactivated': 'Deactivated',
    'deactivated_title': 'This account is deactivated',
    'deactivated_body':
        'All grants are ineffective while the account is inactive. History remains available and permissions are read only.',
    'shadow_mode': 'Shadow mode',
    'shadow_title': 'Access comparison is in shadow mode',
    'shadow_body':
        'The resolver is showing parity information. Only enforced and assignable permissions can be changed.',
    'enforced_mode': 'Enforced',
    'mixed_mode': 'Mixed rollout',
    'mixed_title': 'Permissions are being enabled progressively',
    'mixed_body':
        'Enforced rows can be managed. Shadow rows remain read-only while their candidate decision is compared with current production access.',
    'authoritative': 'Current production access',
    'candidate': 'Candidate access',
    'parity_match': 'Parity confirmed',
    'parity_difference': 'Parity difference',
    'protected': 'Protected',
    'protected_help':
        'This permission or workflow rule cannot be weakened from User Management.',
    'planned': 'Planned',
    'planned_help':
        'This permission is visible for planning but has no production consumer yet.',
    'assignable': 'Assignable',
    'not_assignable': 'Read only',
    'allowed': 'Allowed',
    'denied': 'Denied',
    'inherited': 'Inherited',
    'all_projects': 'All eligible projects',
    'selected_projects': 'Selected projects',
    'project_specific_summary': 'Project-specific access',
    'allowed_project_count': '{allowed} of {count} visible projects allowed',
    'organization_summary_hidden':
        'Organization-wide access is hidden outside your delegation scope.',
    'requires_project_access': 'Requires active project access',
    'no_project_access': 'No eligible project access',
    'project_count': '{count} projects',
    'edit_access': 'Edit access',
    'manage_access': 'Manage access',
    'manage_user': 'Manage',
    'role_family.engineering': 'Engineering',
    'role_family.procurement': 'Procurement',
    'role_family.admin': 'Administration',
    'deactivate_account_short': 'Deactivate',
    'deactivate_account': 'Deactivate account',
    'deactivate_account_title': 'Deactivate account?',
    'deactivate_account_body':
        '{name} will no longer be able to sign in. Their project and audit history will be retained.',
    'delete_local_user': 'Delete local user',
    'delete_local_user_title': 'Delete local user?',
    'delete_local_user_body':
        'Remove {name} from this local development roster?',
    'deactivate_account_success': '{name} deactivated',
    'delete_local_user_success': '{name} removed from the local roster',
    'account_reactivated': 'Account reactivated',
    'account_deactivated': 'Account deactivated',
    'last_admin_deactivation_error':
        'The only active admin cannot be deactivated. Assign another admin first.',
    'self_account_protected': 'Your signed-in account is protected',
    'self_account_protected_body':
        'You cannot deactivate or change roles for your own account. Ask another authorized administrator.',
    'directory_loading_title': 'Verifying directory access…',
    'directory_unavailable_title': 'User directory access is unavailable',
    'directory_unavailable_body':
        'Your confirmed access may have changed, or the permission service needs to reconnect.',
    'admin_options_loading': 'Verifying assignable roles and account actions…',
    'admin_options_unavailable':
        'Role and account controls are unavailable until the protected server confirms this target.',
    'no_assignable_roles':
        'No roles are available within your delegation scope.',
    'role_options_help':
        'Only exact roles confirmed by the protected server are shown.',
    'use_role_default': 'Use role default',
    'grant_access': 'Grant access',
    'deny_access': 'Deny access',
    'select_scope': 'Select scope',
    'organization_scope': 'Organization scope',
    'project_scope_label': 'Specific projects',
    'select_projects': 'Select projects',
    'select_at_least_one_project': 'Select at least one eligible project.',
    'review_change': 'Review access change',
    'review_changes': 'Review change',
    'stage_assignment': 'Add or replace an assignment',
    'stage_assignment_help':
        'Choose an effect and scope. Nothing changes until the complete review is saved.',
    'stage_change': 'Stage change',
    'no_change_selected': 'Select an assignment to add or remove.',
    'set_expiry': 'Set an expiry date',
    'choose_expiry': 'Choose expiry date',
    'continuity_assignment_policy':
        'This administration permission takes effect immediately and remains open-ended to protect access continuity. Scheduling and expiry are unavailable.',
    'before': 'Before',
    'after': 'After',
    'reason': 'Reason for change',
    'reason_hint':
        'Explain why this person needs the access change (minimum 8 characters).',
    'reason_required': 'Enter a meaningful reason of at least 8 characters.',
    'server_confirmed_notice':
        'The server will re-check your authority, scope and the latest revision before saving.',
    'save_change': 'Save access change',
    'saving': 'Saving…',
    'cancel': 'Cancel',
    'close': 'Close',
    'discard': 'Discard change',
    'retry': 'Try again',
    'refresh': 'Refresh',
    'refreshing': 'Checking latest access…',
    'loading_title': 'Securing this access workspace…',
    'loading_body':
        'Verifying the user, permissions and current server revision.',
    'load_failed_title': 'Access could not be loaded',
    'load_failed_body':
        'No permission controls are available until the protected server confirms this workspace.',
    'forbidden_title': 'You cannot view this access workspace',
    'forbidden_body':
        'Your current account does not have permission to inspect this user’s access.',
    'offline_title': 'Connect to manage access',
    'offline_body':
        'Permission changes require a live server confirmation. Reconnect, then try again.',
    'conflict_title': 'Access changed on another device',
    'conflict_body':
        'Your intended change is still here. Reload the latest revision, review it again and then save.',
    'reload_latest': 'Reload latest access',
    'keep_reviewing': 'Keep reviewing',
    'save_succeeded': 'Access updated',
    'save_failed': 'The access change was not saved.',
    'invalid_change': 'Review the effect, scope and reason, then try again.',
    'server_rejected': 'The protected permission service rejected this change.',
    'unexpected_response':
        'The server did not return a valid permission confirmation.',
    'empty_title': 'No permissions match',
    'empty_body': 'Clear the search or choose another module.',
    'no_history_title': 'No permission changes yet',
    'no_history_body':
        'Role-baseline access is preserved. Future assignment changes will appear here.',
    'changed_by': 'Changed by {actor}',
    'changed_on': 'Server time {time}',
    'valid_from': 'Valid from',
    'valid_until': 'Valid until',
    'no_expiry': 'No expiry',
    'revision': 'Revision {revision}',
    'role': 'Role',
    'account': 'Account',
    'unassigned': 'Unassigned',
    'system_actor': 'System migration',
    'source': 'Source',
    'scope': 'Scope',
    'runtime': 'Runtime',
    'risk': 'Risk',
    'effect.inherit': 'Use role default',
    'effect.grant': 'Grant',
    'effect.deny': 'Deny',
    'source.explicit_deny': 'Custom denial',
    'source.explicit_grant': 'Custom grant',
    'source.legacy_override': 'Preserved legacy override',
    'source.role_default': 'Role default',
    'source.inactive': 'Inactive account',
    'source.planned_disabled': 'Planned and disabled',
    'source.none': 'No access',
    'scope.organization': 'Organization',
    'scope.project': 'Project',
    'risk.low': 'Low risk',
    'risk.medium': 'Medium risk',
    'risk.high': 'High risk',
    'risk.critical': 'Critical',
    'history.set': 'Assignment saved',
    'history.clear': 'Assignment cleared',
    'history.migration': 'Preserved during migration',
    'module.projects': 'Projects',
    'module.boq': 'BOQ',
    'module.material_requests': 'Material Requests',
    'module.inventory': 'Inventory',
    'module.material_returns': 'Material Returns',
    'module.documents': 'Documents',
    'module.team_chat': 'Team Chat',
    'module.configuration': 'Configuration',
    'module.users': 'User Management',
    'module.audit': 'Audit Trail',
    'module.rentals': 'Rental Properties',
    'module.commercials': 'Commercial information',
    'module.accounts': 'Accounts',
    'action.view': 'View',
    'action.create': 'Create',
    'action.edit': 'Edit',
    'action.submit': 'Submit',
    'action.approve': 'Approve',
    'action.arrange': 'Arrange',
    'action.dispatch': 'Dispatch',
    'action.receive': 'Review receipt',
    'action.close': 'Close',
    'action.archive': 'Archive',
    'action.manage_members': 'Manage project members',
    'action.import': 'Import',
    'action.export': 'Export',
    'action.adjust_stock': 'Adjust stock',
    'action.manage_items': 'Manage items',
    'action.manage_categories': 'Manage categories',
    'action.manage_groups': 'Manage groups',
    'action.announce': 'Create announcements',
    'action.upload': 'Upload and link',
    'action.manage_versions': 'Manage versions',
    'action.stage': 'Stage changes',
    'action.publish': 'Publish',
    'action.manage_accounts': 'Manage accounts',
    'action.manage_permissions': 'Manage permissions',
    'action.corrective_note': 'Append corrective note',
    'role.project_engineer': 'Project Engineer',
    'role.site_engineer': 'Site Engineer',
    'role.senior_mechanical_engineer': 'Senior Mechanical Engineer',
    'role.project_manager': 'Project Manager',
    'role.workshop_in_charge': 'Workshop In-Charge',
    'role.document_controller': 'Document Controller',
    'role.procurement': 'Procurement',
    'role.admin': 'Admin',
  };

  static const Map<String, Map<String, String>> _localized = {
    'ar': {
      'title': 'الصلاحيات المحددة',
      'subtitle':
          'راجع الصلاحية الفعلية ومصدرها ونطاق المشروع قبل حفظ أي تغيير مدقق.',
      'back_to_users': 'العودة إلى إدارة المستخدمين',
      'search_permissions': 'البحث في الصلاحيات',
      'search_hint': 'ابحث عن وحدة أو إجراء…',
      'all_modules': 'جميع الوحدات',
      'effective_access': 'الصلاحية الفعلية',
      'role_baseline': 'صلاحيات الدور الأساسية',
      'custom_assignments': 'التعيينات المخصصة',
      'permission_history': 'سجل الصلاحيات',
      'permissions': 'الصلاحيات',
      'active': 'نشط',
      'deactivated': 'معطل',
      'deactivated_title': 'هذا الحساب معطل',
      'deactivated_body':
          'جميع المنح غير فعالة أثناء تعطيل الحساب. يبقى السجل متاحًا والصلاحيات للقراءة فقط.',
      'shadow_mode': 'وضع المطابقة',
      'shadow_title': 'مقارنة الصلاحيات تعمل في وضع المطابقة',
      'shadow_body':
          'يعرض النظام معلومات المطابقة. يمكن تغيير الصلاحيات المفعلة والقابلة للتعيين فقط.',
      'enforced_mode': 'مُفعّل',
      'mixed_mode': 'تفعيل تدريجي',
      'mixed_title': 'يتم تفعيل الصلاحيات تدريجيًا',
      'mixed_body':
          'يمكن إدارة الصفوف المفعلة. تبقى صفوف المطابقة للقراءة فقط أثناء مقارنة القرار المرشح بصلاحية الإنتاج الحالية.',
      'authoritative': 'صلاحية الإنتاج الحالية',
      'candidate': 'الصلاحية المرشحة',
      'parity_match': 'تم تأكيد المطابقة',
      'parity_difference': 'اختلاف في المطابقة',
      'protected': 'محمي',
      'planned': 'مخطط',
      'not_assignable': 'للقراءة فقط',
      'allowed': 'مسموح',
      'denied': 'مرفوض',
      'inherited': 'موروث',
      'all_projects': 'جميع المشاريع المؤهلة',
      'selected_projects': 'المشاريع المحددة',
      'project_specific_summary': 'صلاحية خاصة بكل مشروع',
      'allowed_project_count': 'مسموح في {allowed} من {count} مشاريع ظاهرة',
      'organization_summary_hidden':
          'صلاحية المؤسسة مخفية خارج نطاق التفويض الخاص بك.',
      'requires_project_access': 'يتطلب وصولاً نشطًا للمشروع',
      'no_project_access': 'لا يوجد وصول مؤهل للمشروع',
      'edit_access': 'تعديل الصلاحية',
      'manage_access': 'إدارة الصلاحيات',
      'manage_user': 'إدارة',
      'role_family.engineering': 'الهندسة',
      'role_family.procurement': 'المشتريات',
      'role_family.admin': 'الإدارة',
      'deactivate_account_short': 'تعطيل',
      'deactivate_account': 'تعطيل الحساب',
      'deactivate_account_title': 'تعطيل الحساب؟',
      'deactivate_account_body':
          'لن يتمكن {name} من تسجيل الدخول. سيتم الاحتفاظ بسجل المشاريع والتدقيق.',
      'delete_local_user': 'حذف المستخدم المحلي',
      'delete_local_user_title': 'حذف المستخدم المحلي؟',
      'delete_local_user_body': 'إزالة {name} من قائمة التطوير المحلية؟',
      'deactivate_account_success': 'تم تعطيل {name}',
      'delete_local_user_success': 'تمت إزالة {name} من القائمة المحلية',
      'account_reactivated': 'تمت إعادة تفعيل الحساب',
      'account_deactivated': 'تم تعطيل الحساب',
      'last_admin_deactivation_error':
          'لا يمكن تعطيل المسؤول النشط الوحيد. عيّن مسؤولاً آخر أولاً.',
      'self_account_protected': 'حسابك الحالي محمي',
      'self_account_protected_body':
          'لا يمكنك تعطيل حسابك أو تغيير أدواره. اطلب ذلك من مسؤول آخر مخول.',
      'directory_loading_title': 'جارٍ التحقق من صلاحية دليل المستخدمين…',
      'directory_unavailable_title': 'صلاحية دليل المستخدمين غير متاحة',
      'directory_unavailable_body':
          'ربما تغيرت صلاحيتك المؤكدة أو تحتاج خدمة الصلاحيات إلى إعادة الاتصال.',
      'admin_options_loading':
          'جارٍ التحقق من الأدوار وإجراءات الحساب المسموح بها…',
      'admin_options_unavailable':
          'لن تتوفر ضوابط الدور والحساب حتى يؤكد الخادم المحمي هذا المستخدم.',
      'no_assignable_roles': 'لا توجد أدوار ضمن نطاق التفويض الخاص بك.',
      'role_options_help':
          'يتم عرض الأدوار الدقيقة التي أكدها الخادم المحمي فقط.',
      'use_role_default': 'استخدام إعداد الدور',
      'grant_access': 'منح الصلاحية',
      'deny_access': 'رفض الصلاحية',
      'select_scope': 'تحديد النطاق',
      'organization_scope': 'نطاق المؤسسة',
      'project_scope_label': 'مشاريع محددة',
      'select_projects': 'اختيار المشاريع',
      'select_at_least_one_project': 'اختر مشروعًا مؤهلاً واحدًا على الأقل.',
      'review_change': 'مراجعة تغيير الصلاحية',
      'stage_assignment': 'إضافة أو استبدال تعيين',
      'stage_assignment_help':
          'حدد التأثير والنطاق. لن يتغير شيء حتى حفظ المراجعة الكاملة.',
      'stage_change': 'تجهيز التغيير',
      'no_change_selected': 'حدد تعيينًا لإضافته أو إزالته.',
      'set_expiry': 'تحديد تاريخ انتهاء',
      'choose_expiry': 'اختيار تاريخ الانتهاء',
      'continuity_assignment_policy':
          'تسري صلاحية الإدارة هذه فورًا وتبقى مفتوحة لحماية استمرارية الوصول. الجدولة وتاريخ الانتهاء غير متاحين.',
      'reason': 'سبب التغيير',
      'reason_hint': 'وضح سبب حاجة هذا الشخص إلى تغيير الصلاحية.',
      'reason_required': 'أدخل سببًا واضحًا من 8 أحرف على الأقل.',
      'save_change': 'حفظ تغيير الصلاحية',
      'saving': 'جارٍ الحفظ…',
      'cancel': 'إلغاء',
      'discard': 'تجاهل التغيير',
      'retry': 'إعادة المحاولة',
      'refresh': 'تحديث',
      'refreshing': 'جارٍ التحقق من أحدث الصلاحيات…',
      'loading_title': 'جارٍ تأمين مساحة الصلاحيات…',
      'loading_body':
          'جارٍ التحقق من المستخدم والصلاحيات وإصدار الخادم الحالي.',
      'load_failed_title': 'تعذر تحميل الصلاحيات',
      'forbidden_title': 'لا يمكنك عرض مساحة الصلاحيات هذه',
      'offline_title': 'اتصل بالشبكة لإدارة الصلاحيات',
      'conflict_title': 'تغيرت الصلاحيات على جهاز آخر',
      'conflict_body':
          'التغيير المقصود ما زال محفوظًا. حمّل أحدث إصدار وراجعه ثم احفظه.',
      'reload_latest': 'تحميل أحدث الصلاحيات',
      'save_succeeded': 'تم تحديث الصلاحيات',
      'save_failed': 'لم يتم حفظ تغيير الصلاحية.',
      'empty_title': 'لا توجد صلاحيات مطابقة',
      'no_history_title': 'لا توجد تغييرات في الصلاحيات بعد',
      'source': 'المصدر',
      'scope': 'النطاق',
      'runtime': 'التشغيل',
      'risk': 'المخاطر',
      'effect.inherit': 'استخدام إعداد الدور',
      'effect.grant': 'منح',
      'effect.deny': 'رفض',
      'source.explicit_deny': 'رفض مخصص',
      'source.explicit_grant': 'منح مخصص',
      'source.legacy_override': 'تجاوز قديم محفوظ',
      'source.role_default': 'إعداد الدور',
      'source.inactive': 'حساب غير نشط',
      'source.planned_disabled': 'مخطط ومعطل',
      'source.none': 'بدون صلاحية',
      'scope.organization': 'المؤسسة',
      'scope.project': 'المشروع',
      'history.set': 'تم حفظ التعيين',
      'history.clear': 'تم مسح التعيين',
      'history.migration': 'تم الحفظ أثناء الترحيل',
      'module.projects': 'المشاريع',
      'module.boq': 'جدول الكميات',
      'module.material_requests': 'طلبات المواد',
      'module.inventory': 'المخزون',
      'module.material_returns': 'مرتجعات المواد',
      'module.documents': 'المستندات',
      'module.team_chat': 'محادثة الفريق',
      'module.configuration': 'الإعدادات',
      'module.users': 'إدارة المستخدمين',
      'module.audit': 'سجل التدقيق',
      'module.rentals': 'العقارات المؤجرة',
      'module.commercials': 'المعلومات التجارية',
      'module.accounts': 'الحسابات',
      'action.view': 'عرض',
      'action.create': 'إنشاء',
      'action.edit': 'تعديل',
      'action.submit': 'إرسال',
      'action.approve': 'اعتماد',
      'action.arrange': 'ترتيب',
      'action.dispatch': 'إرسال للموقع',
      'action.receive': 'مراجعة الاستلام',
      'action.close': 'إغلاق',
      'action.archive': 'أرشفة',
      'action.import': 'استيراد',
      'action.export': 'تصدير',
      'action.publish': 'نشر',
      'action.manage_permissions': 'إدارة الصلاحيات',
      'role.project_engineer': 'مهندس المشروع',
      'role.site_engineer': 'مهندس الموقع',
      'role.senior_mechanical_engineer': 'مهندس ميكانيكي أول',
      'role.project_manager': 'مدير المشروع',
      'role.workshop_in_charge': 'مسؤول الورشة',
      'role.document_controller': 'مراقب المستندات',
      'role.procurement': 'المشتريات',
      'role.admin': 'المسؤول',
    },
    'ur': {
      'title': 'مخصوص رسائی',
      'subtitle':
          'محفوظ شدہ تبدیلی سے پہلے مؤثر رسائی، اس کا ذریعہ اور پروجیکٹ دائرہ دیکھیں۔',
      'back_to_users': 'صارف انتظام پر واپس جائیں',
      'search_permissions': 'اجازتیں تلاش کریں',
      'search_hint': 'ماڈیول یا کارروائی تلاش کریں…',
      'all_modules': 'تمام ماڈیولز',
      'effective_access': 'مؤثر رسائی',
      'role_baseline': 'کردار کی بنیادی اجازت',
      'custom_assignments': 'مخصوص اجازتیں',
      'permission_history': 'اجازت کی تاریخ',
      'permissions': 'اجازتیں',
      'active': 'فعال',
      'deactivated': 'غیر فعال',
      'deactivated_title': 'یہ اکاؤنٹ غیر فعال ہے',
      'deactivated_body':
          'اکاؤنٹ غیر فعال ہونے پر تمام اجازتیں غیر مؤثر ہیں۔ تاریخ دستیاب اور اجازتیں صرف مطالعہ کے لیے رہتی ہیں۔',
      'shadow_mode': 'تقابلی موڈ',
      'shadow_title': 'رسائی کا موازنہ تقابلی موڈ میں ہے',
      'shadow_body':
          'حل کنندہ تقابلی معلومات دکھا رہا ہے۔ صرف نافذ اور قابل تفویض اجازت بدلی جا سکتی ہے۔',
      'enforced_mode': 'نافذ',
      'mixed_mode': 'مرحلہ وار نفاذ',
      'mixed_title': 'اجازتیں مرحلہ وار نافذ ہو رہی ہیں',
      'mixed_body':
          'نافذ قطاریں منظم کی جا سکتی ہیں۔ تقابلی قطاریں موجودہ پیداواری رسائی سے موازنہ کے دوران صرف مطالعہ رہتی ہیں۔',
      'authoritative': 'موجودہ پیداواری رسائی',
      'candidate': 'امیدوار رسائی',
      'parity_match': 'مطابقت کی تصدیق',
      'parity_difference': 'مطابقت میں فرق',
      'protected': 'محفوظ',
      'planned': 'منصوبہ بند',
      'not_assignable': 'صرف مطالعہ',
      'allowed': 'اجازت ہے',
      'denied': 'اجازت نہیں',
      'inherited': 'کردار سے حاصل',
      'all_projects': 'تمام اہل پروجیکٹس',
      'selected_projects': 'منتخب پروجیکٹس',
      'project_specific_summary': 'پروجیکٹ کے مطابق رسائی',
      'allowed_project_count':
          '{count} نظر آنے والے پروجیکٹس میں سے {allowed} کی اجازت',
      'organization_summary_hidden':
          'ادارے کی سطح کی رسائی آپ کے تفویض دائرے سے باہر پوشیدہ ہے۔',
      'requires_project_access': 'فعال پروجیکٹ رسائی ضروری ہے',
      'manage_access': 'رسائی منظم کریں',
      'manage_user': 'منظم کریں',
      'role_family.engineering': 'انجینئرنگ',
      'role_family.procurement': 'پروکیورمنٹ',
      'role_family.admin': 'انتظامیہ',
      'deactivate_account_short': 'غیر فعال کریں',
      'deactivate_account': 'اکاؤنٹ غیر فعال کریں',
      'deactivate_account_title': 'اکاؤنٹ غیر فعال کریں؟',
      'deactivate_account_body':
          '{name} اب سائن اِن نہیں کر سکیں گے۔ ان کی پروجیکٹ اور آڈٹ تاریخ محفوظ رہے گی۔',
      'delete_local_user': 'مقامی صارف حذف کریں',
      'delete_local_user_title': 'مقامی صارف حذف کریں؟',
      'delete_local_user_body': '{name} کو مقامی ترقیاتی فہرست سے ہٹائیں؟',
      'deactivate_account_success': '{name} غیر فعال کر دیا گیا',
      'delete_local_user_success': '{name} کو مقامی فہرست سے ہٹا دیا گیا',
      'account_reactivated': 'اکاؤنٹ دوبارہ فعال کر دیا گیا',
      'account_deactivated': 'اکاؤنٹ غیر فعال کر دیا گیا',
      'last_admin_deactivation_error':
          'واحد فعال ایڈمن کو غیر فعال نہیں کیا جا سکتا۔ پہلے دوسرا ایڈمن مقرر کریں۔',
      'self_account_protected': 'آپ کا موجودہ اکاؤنٹ محفوظ ہے',
      'self_account_protected_body':
          'آپ اپنے اکاؤنٹ کو غیر فعال یا اس کے کردار تبدیل نہیں کر سکتے۔ کسی دوسرے مجاز ایڈمن سے کہیں۔',
      'directory_loading_title': 'صارف ڈائریکٹری رسائی کی تصدیق ہو رہی ہے…',
      'directory_unavailable_title': 'صارف ڈائریکٹری رسائی دستیاب نہیں',
      'directory_unavailable_body':
          'آپ کی تصدیق شدہ رسائی بدل گئی ہو سکتی ہے، یا اجازت سروس کو دوبارہ جڑنے کی ضرورت ہے۔',
      'admin_options_loading':
          'قابل تفویض کرداروں اور اکاؤنٹ اقدامات کی تصدیق ہو رہی ہے…',
      'admin_options_unavailable':
          'محفوظ سرور کی تصدیق تک کردار اور اکاؤنٹ کنٹرول دستیاب نہیں ہوں گے۔',
      'no_assignable_roles':
          'آپ کے تفویض کے دائرے میں کوئی کردار دستیاب نہیں ہے۔',
      'role_options_help':
          'صرف محفوظ سرور سے تصدیق شدہ درست کردار دکھائے جاتے ہیں۔',
      'use_role_default': 'کردار کی بنیادی اجازت',
      'grant_access': 'رسائی دیں',
      'deny_access': 'رسائی روکیں',
      'review_change': 'رسائی کی تبدیلی دیکھیں',
      'stage_assignment': 'اجازت شامل یا تبدیل کریں',
      'stage_assignment_help':
          'اثر اور دائرہ منتخب کریں۔ مکمل جائزہ محفوظ ہونے تک کچھ نہیں بدلے گا۔',
      'stage_change': 'تبدیلی تیار کریں',
      'no_change_selected': 'شامل یا ختم کرنے کے لیے اجازت منتخب کریں۔',
      'set_expiry': 'اختتامی تاریخ مقرر کریں',
      'choose_expiry': 'اختتامی تاریخ منتخب کریں',
      'continuity_assignment_policy':
          'رسائی کے تسلسل کے تحفظ کے لیے یہ انتظامی اجازت فوراً نافذ ہوتی ہے اور بغیر اختتام جاری رہتی ہے۔ شیڈولنگ اور میعاد دستیاب نہیں ہیں۔',
      'reason': 'تبدیلی کی وجہ',
      'reason_hint': 'واضح کریں کہ اس شخص کو یہ تبدیلی کیوں درکار ہے۔',
      'reason_required': 'کم از کم 8 حروف کی واضح وجہ درج کریں۔',
      'save_change': 'رسائی کی تبدیلی محفوظ کریں',
      'saving': 'محفوظ ہو رہا ہے…',
      'cancel': 'منسوخ',
      'retry': 'دوبارہ کوشش',
      'refresh': 'تازہ کریں',
      'loading_title': 'رسائی کی جگہ محفوظ کی جا رہی ہے…',
      'load_failed_title': 'رسائی لوڈ نہ ہو سکی',
      'forbidden_title': 'آپ یہ رسائی نہیں دیکھ سکتے',
      'offline_title': 'رسائی منظم کرنے کے لیے انٹرنیٹ سے جڑیں',
      'conflict_title': 'رسائی کسی دوسرے آلے پر بدل گئی',
      'reload_latest': 'تازہ ترین رسائی لوڈ کریں',
      'save_succeeded': 'رسائی اپ ڈیٹ ہو گئی',
      'save_failed': 'رسائی کی تبدیلی محفوظ نہیں ہوئی۔',
      'empty_title': 'کوئی اجازت میل نہیں کھاتی',
      'no_history_title': 'ابھی کوئی اجازت تبدیل نہیں ہوئی',
      'effect.inherit': 'کردار کی بنیادی اجازت',
      'effect.grant': 'اجازت دیں',
      'effect.deny': 'اجازت روکیں',
      'source.explicit_deny': 'مخصوص پابندی',
      'source.explicit_grant': 'مخصوص اجازت',
      'source.role_default': 'کردار کی بنیادی اجازت',
      'scope.organization': 'ادارہ',
      'scope.project': 'پروجیکٹ',
      'module.projects': 'پروجیکٹس',
      'module.boq': 'مقدار کی فہرست',
      'module.material_requests': 'مواد کی درخواستیں',
      'module.inventory': 'انوینٹری',
      'module.material_returns': 'مواد کی واپسی',
      'module.documents': 'دستاویزات',
      'module.team_chat': 'ٹیم چیٹ',
      'module.configuration': 'ترتیبات',
      'module.users': 'صارف انتظام',
      'module.audit': 'آڈٹ ٹریل',
      'module.rentals': 'کرایہ کی جائیدادیں',
      'module.accounts': 'اکاؤنٹس',
      'action.view': 'دیکھیں',
      'action.create': 'بنائیں',
      'action.edit': 'تبدیل کریں',
      'action.submit': 'جمع کریں',
      'action.approve': 'منظور کریں',
      'action.import': 'درآمد',
      'action.export': 'برآمد',
      'action.manage_permissions': 'اجازتیں منظم کریں',
      'role.project_engineer': 'پراجیکٹ انجینئر',
      'role.site_engineer': 'سائٹ انجینئر',
      'role.senior_mechanical_engineer': 'سینئر مکینیکل انجینئر',
      'role.project_manager': 'پراجیکٹ مینیجر',
      'role.workshop_in_charge': 'ورکشاپ انچارج',
      'role.document_controller': 'دستاویز کنٹرولر',
      'role.procurement': 'پروکیورمنٹ',
      'role.admin': 'ایڈمن',
    },
    'hi': {
      'title': 'सीमित पहुँच',
      'subtitle':
          'ऑडिट किए गए बदलाव से पहले प्रभावी पहुँच, उसका स्रोत और प्रोजेक्ट दायरा देखें।',
      'back_to_users': 'उपयोगकर्ता प्रबंधन पर वापस जाएँ',
      'search_permissions': 'अनुमतियाँ खोजें',
      'search_hint': 'मॉड्यूल या कार्रवाई खोजें…',
      'all_modules': 'सभी मॉड्यूल',
      'effective_access': 'प्रभावी पहुँच',
      'role_baseline': 'भूमिका की मूल अनुमति',
      'custom_assignments': 'विशेष अनुमतियाँ',
      'permission_history': 'अनुमति इतिहास',
      'permissions': 'अनुमतियाँ',
      'active': 'सक्रिय',
      'deactivated': 'निष्क्रिय',
      'deactivated_title': 'यह खाता निष्क्रिय है',
      'deactivated_body':
          'खाता निष्क्रिय होने पर सभी अनुदान अप्रभावी हैं। इतिहास उपलब्ध और अनुमतियाँ केवल पढ़ने योग्य रहती हैं।',
      'shadow_mode': 'तुलना मोड',
      'shadow_title': 'पहुँच तुलना मोड में है',
      'shadow_body':
          'रिज़ॉल्वर तुलना जानकारी दिखा रहा है। केवल लागू और असाइन करने योग्य अनुमतियाँ बदली जा सकती हैं।',
      'enforced_mode': 'लागू',
      'mixed_mode': 'क्रमिक लागूकरण',
      'mixed_title': 'अनुमतियाँ क्रमिक रूप से लागू हो रही हैं',
      'mixed_body':
          'लागू पंक्तियाँ प्रबंधित की जा सकती हैं। तुलना पंक्तियाँ वर्तमान उत्पादन पहुँच से मिलान के दौरान केवल पढ़ने योग्य रहती हैं।',
      'authoritative': 'वर्तमान उत्पादन पहुँच',
      'candidate': 'प्रस्तावित पहुँच',
      'parity_match': 'मिलान की पुष्टि',
      'parity_difference': 'मिलान में अंतर',
      'protected': 'सुरक्षित',
      'planned': 'योजनाबद्ध',
      'not_assignable': 'केवल पढ़ें',
      'allowed': 'अनुमत',
      'denied': 'अस्वीकृत',
      'inherited': 'भूमिका से प्राप्त',
      'all_projects': 'सभी योग्य प्रोजेक्ट',
      'selected_projects': 'चुने हुए प्रोजेक्ट',
      'project_specific_summary': 'प्रोजेक्ट-विशिष्ट पहुँच',
      'allowed_project_count':
          '{count} दिखने वाले प्रोजेक्ट में से {allowed} अनुमत',
      'organization_summary_hidden':
          'संगठन-स्तरीय पहुँच आपकी प्रतिनिधि सीमा के बाहर छिपी है।',
      'requires_project_access': 'सक्रिय प्रोजेक्ट पहुँच आवश्यक है',
      'manage_access': 'पहुँच प्रबंधित करें',
      'manage_user': 'प्रबंधित करें',
      'role_family.engineering': 'इंजीनियरिंग',
      'role_family.procurement': 'खरीद',
      'role_family.admin': 'प्रशासन',
      'deactivate_account_short': 'निष्क्रिय करें',
      'deactivate_account': 'खाता निष्क्रिय करें',
      'deactivate_account_title': 'खाता निष्क्रिय करें?',
      'deactivate_account_body':
          '{name} अब साइन इन नहीं कर सकेंगे। उनका प्रोजेक्ट और ऑडिट इतिहास सुरक्षित रहेगा।',
      'delete_local_user': 'स्थानीय उपयोगकर्ता हटाएँ',
      'delete_local_user_title': 'स्थानीय उपयोगकर्ता हटाएँ?',
      'delete_local_user_body': '{name} को स्थानीय विकास सूची से हटाएँ?',
      'deactivate_account_success': '{name} निष्क्रिय किया गया',
      'delete_local_user_success': '{name} को स्थानीय सूची से हटा दिया गया',
      'account_reactivated': 'खाता फिर सक्रिय किया गया',
      'account_deactivated': 'खाता निष्क्रिय किया गया',
      'last_admin_deactivation_error':
          'एकमात्र सक्रिय एडमिन को निष्क्रिय नहीं किया जा सकता। पहले दूसरा एडमिन नियुक्त करें।',
      'self_account_protected': 'आपका साइन-इन खाता सुरक्षित है',
      'self_account_protected_body':
          'आप अपने खाते को निष्क्रिय या उसकी भूमिकाएँ नहीं बदल सकते। किसी अन्य अधिकृत एडमिन से कहें।',
      'directory_loading_title': 'उपयोगकर्ता निर्देशिका पहुँच जाँची जा रही है…',
      'directory_unavailable_title':
          'उपयोगकर्ता निर्देशिका पहुँच उपलब्ध नहीं है',
      'directory_unavailable_body':
          'आपकी पुष्ट पहुँच बदल गई हो सकती है, या अनुमति सेवा को फिर से जुड़ना होगा।',
      'admin_options_loading':
          'सौंपने योग्य भूमिकाओं और खाता कार्रवाइयों की पुष्टि हो रही है…',
      'admin_options_unavailable':
          'सुरक्षित सर्वर द्वारा इस उपयोगकर्ता की पुष्टि होने तक भूमिका और खाता नियंत्रण उपलब्ध नहीं हैं।',
      'no_assignable_roles':
          'आपकी प्रतिनिधि सीमा में कोई भूमिका उपलब्ध नहीं है।',
      'role_options_help':
          'केवल सुरक्षित सर्वर द्वारा पुष्टि की गई सटीक भूमिकाएँ दिखाई जाती हैं।',
      'use_role_default': 'भूमिका की मूल अनुमति',
      'grant_access': 'पहुँच दें',
      'deny_access': 'पहुँच रोकें',
      'review_change': 'पहुँच बदलाव की समीक्षा करें',
      'stage_assignment': 'अनुमति जोड़ें या बदलें',
      'stage_assignment_help':
          'प्रभाव और दायरा चुनें। पूरी समीक्षा सहेजने तक कुछ नहीं बदलेगा।',
      'stage_change': 'बदलाव तैयार करें',
      'no_change_selected': 'जोड़ने या हटाने के लिए अनुमति चुनें।',
      'set_expiry': 'समाप्ति तिथि निर्धारित करें',
      'choose_expiry': 'समाप्ति तिथि चुनें',
      'continuity_assignment_policy':
          'पहुँच की निरंतरता सुरक्षित रखने के लिए यह प्रशासनिक अनुमति तुरंत लागू होती है और बिना समाप्ति जारी रहती है। समय-निर्धारण और समाप्ति उपलब्ध नहीं हैं।',
      'reason': 'बदलाव का कारण',
      'reason_hint': 'बताएँ कि इस व्यक्ति को यह पहुँच बदलाव क्यों चाहिए।',
      'reason_required': 'कम से कम 8 अक्षरों का स्पष्ट कारण दर्ज करें।',
      'save_change': 'पहुँच बदलाव सहेजें',
      'saving': 'सहेजा जा रहा है…',
      'cancel': 'रद्द करें',
      'retry': 'फिर कोशिश करें',
      'refresh': 'रीफ़्रेश',
      'loading_title': 'पहुँच कार्यक्षेत्र सुरक्षित किया जा रहा है…',
      'load_failed_title': 'पहुँच लोड नहीं हो सकी',
      'forbidden_title': 'आप इस पहुँच को नहीं देख सकते',
      'offline_title': 'पहुँच प्रबंधित करने के लिए कनेक्ट करें',
      'conflict_title': 'पहुँच किसी दूसरे डिवाइस पर बदल गई',
      'reload_latest': 'नवीनतम पहुँच लोड करें',
      'save_succeeded': 'पहुँच अपडेट हो गई',
      'save_failed': 'पहुँच बदलाव सहेजा नहीं गया।',
      'empty_title': 'कोई अनुमति मेल नहीं खाती',
      'no_history_title': 'अभी कोई अनुमति बदलाव नहीं है',
      'effect.inherit': 'भूमिका की मूल अनुमति',
      'effect.grant': 'अनुमति दें',
      'effect.deny': 'अनुमति रोकें',
      'source.explicit_deny': 'विशेष रोक',
      'source.explicit_grant': 'विशेष अनुमति',
      'source.role_default': 'भूमिका की मूल अनुमति',
      'scope.organization': 'संगठन',
      'scope.project': 'प्रोजेक्ट',
      'module.projects': 'प्रोजेक्ट',
      'module.boq': 'मात्रा सूची',
      'module.material_requests': 'सामग्री अनुरोध',
      'module.inventory': 'इन्वेंटरी',
      'module.material_returns': 'सामग्री वापसी',
      'module.documents': 'दस्तावेज़',
      'module.team_chat': 'टीम चैट',
      'module.configuration': 'कॉन्फ़िगरेशन',
      'module.users': 'उपयोगकर्ता प्रबंधन',
      'module.audit': 'ऑडिट ट्रेल',
      'module.rentals': 'किराये की संपत्तियाँ',
      'module.accounts': 'अकाउंट्स',
      'action.view': 'देखें',
      'action.create': 'बनाएँ',
      'action.edit': 'संपादित करें',
      'action.submit': 'जमा करें',
      'action.approve': 'स्वीकृत करें',
      'action.import': 'आयात',
      'action.export': 'निर्यात',
      'action.manage_permissions': 'अनुमतियाँ प्रबंधित करें',
      'role.project_engineer': 'परियोजना इंजीनियर',
      'role.site_engineer': 'साइट इंजीनियर',
      'role.senior_mechanical_engineer': 'वरिष्ठ मैकेनिकल इंजीनियर',
      'role.project_manager': 'परियोजना प्रबंधक',
      'role.workshop_in_charge': 'कार्यशाला प्रभारी',
      'role.document_controller': 'दस्तावेज़ नियंत्रक',
      'role.procurement': 'खरीद',
      'role.admin': 'एडमिन',
    },
  };
}
