import 'app_language.dart';

/// Localized copy for the normalized R39 Accounts workspace.
abstract final class YorksV1AccountsStrings {
  static const Map<String, Map<String, String>> _copy = {
    'accounts': {
      'en': 'Accounts',
      'ar': 'الحسابات',
      'ur': 'اکاؤنٹس',
      'hi': 'अकाउंट्स',
    },
    'commercial_control': {
      'en': 'Project commercial control',
      'ar': 'الرقابة التجارية للمشاريع',
      'ur': 'پراجیکٹ کمرشل کنٹرول',
      'hi': 'प्रोजेक्ट कमर्शियल कंट्रोल',
    },
    'portfolio_title': {
      'en': 'Accounts Portfolio',
      'ar': 'محفظة الحسابات',
      'ur': 'اکاؤنٹس پورٹ فولیو',
      'hi': 'अकाउंट्स पोर्टफोलियो',
    },
    'portfolio_body': {
      'en':
          'Claimable work, client certification, collections and supplier evidence—connected to each project.',
      'ar':
          'الأعمال القابلة للمطالبة وشهادات العميل والتحصيلات وأدلة الموردين مرتبطة بكل مشروع.',
      'ur':
          'قابلِ کلیم کام، کلائنٹ سرٹیفیکیشن، وصولیاں اور سپلائر ثبوت ہر پراجیکٹ سے منسلک ہیں۔',
      'hi':
          'क्लेम योग्य कार्य, क्लाइंट प्रमाणन, प्राप्तियां और सप्लायर साक्ष्य हर प्रोजेक्ट से जुड़े हैं।',
    },
    'project_accounts': {
      'en': 'Project Accounts',
      'ar': 'حسابات المشروع',
      'ur': 'پراجیکٹ اکاؤنٹس',
      'hi': 'प्रोजेक्ट अकाउंट्स',
    },
    'overview': {
      'en': 'Overview',
      'ar': 'نظرة عامة',
      'ur': 'جائزہ',
      'hi': 'अवलोकन',
    },
    'billing': {
      'en': 'Billing Progress',
      'ar': 'تقدم الفوترة',
      'ur': 'بلنگ پیشرفت',
      'hi': 'बिलिंग प्रगति',
    },
    'invoices': {
      'en': 'Claims & Invoices',
      'ar': 'المطالبات والفواتير',
      'ur': 'کلیمز اور انوائسز',
      'hi': 'क्लेम और इनवॉइस',
    },
    'receipts_pdc': {
      'en': 'Receipts & PDC',
      'ar': 'المقبوضات والشيكات الآجلة',
      'ur': 'رسیدیں اور PDC',
      'hi': 'रसीदें और PDC',
    },
    'supplier_bills': {
      'en': 'Supplier Bills',
      'ar': 'فواتير الموردين',
      'ur': 'سپلائر بلز',
      'hi': 'सप्लायर बिल',
    },
    'documents': {
      'en': 'Documents',
      'ar': 'المستندات',
      'ur': 'دستاویزات',
      'hi': 'दस्तावेज़',
    },
    'activity': {
      'en': 'Activity',
      'ar': 'النشاط',
      'ur': 'سرگرمی',
      'hi': 'गतिविधि',
    },
    'accounts_evidence_register': {'en': 'Accounts Evidence Register'},
    'accounts_evidence_body': {
      'en':
          'Immutable versions, checksums and links keep every commercial file attributable.',
    },
    'accounts_activity_body': {
      'en':
          'A chronological, append-only record of commercial actions and responsibility.',
    },
    'search_documents': {'en': 'Search file name or document type…'},
    'document_type': {'en': 'Document type'},
    'all_document_types': {'en': 'All document types'},
    'upload_document': {'en': 'Upload document'},
    'upload_revision': {'en': 'Upload new revision'},
    'linked_record': {'en': 'Linked record'},
    'classification': {'en': 'Classification'},
    'operational_evidence': {'en': 'Operational evidence'},
    'commercial_evidence': {'en': 'Commercial evidence'},
    'select_file': {'en': 'Select controlled file'},
    'uploading': {'en': 'Uploading…'},
    'no_documents': {'en': 'No Accounts documents match this view'},
    'revision': {'en': 'Revision'},
    'checksum': {'en': 'Checksum'},
    'uploaded_by': {'en': 'Uploaded by'},
    'download': {'en': 'Download'},
    'document_saved': {'en': 'Document saved'},
    'document_cancelled': {'en': 'File selection was cancelled.'},
    'document_failed': {
      'en': 'The document action could not be completed. Try again safely.',
    },
    'filter_entity': {'en': 'Record type'},
    'filter_action': {'en': 'Action code'},
    'all_record_types': {'en': 'All record types'},
    'all_actions': {'en': 'All actions'},
    'no_activity': {'en': 'No Accounts activity matches these filters'},
    'load_more_activity': {'en': 'Load earlier activity'},
    'append_only': {'en': 'Append-only'},
    'before_after_protected': {
      'en': 'Before and after values are shown only with commercial authority.',
    },
    'export_excel': {'en': 'Export Excel'},
    'save_pdf': {'en': 'Save PDF'},
    'print': {'en': 'Print'},
    'preparing_report': {'en': 'Preparing protected report…'},
    'report_saved': {'en': 'Report saved'},
    'report_failed': {
      'en':
          'The protected report could not be generated. Your data is unchanged.',
    },
    'report_actions': {'en': 'Report actions'},
    'support_reference': {'en': 'Support reference'},
    'contract_document': {'en': 'Contract'},
    'contract_variation_document': {'en': 'Contract variation'},
    'progress_evidence_document': {'en': 'Progress evidence'},
    'client_claim_document': {'en': 'Client claim'},
    'client_invoice_document': {'en': 'Client invoice'},
    'client_certification_document': {'en': 'Client certification'},
    'payment_certificate_document': {'en': 'Payment certificate'},
    'pdc_copy_document': {'en': 'PDC copy'},
    'payment_receipt_document': {'en': 'Payment receipt'},
    'supplier_invoice_document': {'en': 'Supplier invoice'},
    'po_lpo_document': {'en': 'PO / LPO'},
    'delivery_receipt_document': {'en': 'Delivery receipt'},
    'payment_advice_document': {'en': 'Payment advice'},
    'commercial_correspondence_document': {'en': 'Commercial correspondence'},
    'other_document': {'en': 'Other'},
    'contract': {
      'en': 'Contract Baseline',
      'ar': 'خط أساس العقد',
      'ur': 'کنٹریکٹ بیس لائن',
      'hi': 'कॉन्ट्रैक्ट बेसलाइन',
    },
    'confirmed': {
      'en': 'Confirmed Eligible',
      'ar': 'المؤكد المؤهل',
      'ur': 'تصدیق شدہ اہل',
      'hi': 'पुष्ट योग्य',
    },
    'available': {
      'en': 'Available to Claim',
      'ar': 'متاح للمطالبة',
      'ur': 'کلیم کے لیے دستیاب',
      'hi': 'क्लेम के लिए उपलब्ध',
    },
    'claimed': {
      'en': 'Yorks Claimed',
      'ar': 'مطالبات يوركس',
      'ur': 'یارکس کلیمڈ',
      'hi': 'यॉर्क्स क्लेम्ड',
    },
    'certified': {
      'en': 'Client Certified',
      'ar': 'معتمد من العميل',
      'ur': 'کلائنٹ سرٹیفائیڈ',
      'hi': 'क्लाइंट प्रमाणित',
    },
    'paid': {
      'en': 'Amount Paid Till Date',
      'ar': 'المبلغ المدفوع حتى تاريخه',
      'ur': 'اب تک ادا شدہ رقم',
      'hi': 'अब तक भुगतान',
    },
    'still_due': {
      'en': 'Still Due',
      'ar': 'المبلغ المستحق',
      'ur': 'ابھی واجب الادا',
      'hi': 'अभी देय',
    },
    'pdc': {
      'en': 'PDC Exposure',
      'ar': 'قيمة الشيكات الآجلة',
      'ur': 'PDC ایکسپوژر',
      'hi': 'PDC एक्सपोज़र',
    },
    'action_required': {
      'en': 'Needs Attention',
      'ar': 'يحتاج إلى اهتمام',
      'ur': 'توجہ درکار',
      'hi': 'ध्यान आवश्यक',
    },
    'projects': {
      'en': 'Project Accounts Register',
      'ar': 'سجل حسابات المشاريع',
      'ur': 'پراجیکٹ اکاؤنٹس رجسٹر',
      'hi': 'प्रोजेक्ट अकाउंट्स रजिस्टर',
    },
    'search': {
      'en': 'Search project, client or reference…',
      'ar': 'ابحث عن مشروع أو عميل أو مرجع…',
      'ur': 'پراجیکٹ، کلائنٹ یا حوالہ تلاش کریں…',
      'hi': 'प्रोजेक्ट, क्लाइंट या संदर्भ खोजें…',
    },
    'filters': {
      'en': 'Filters',
      'ar': 'عوامل التصفية',
      'ur': 'فلٹرز',
      'hi': 'फ़िल्टर',
    },
    'clear': {'en': 'Clear', 'ar': 'مسح', 'ur': 'صاف کریں', 'hi': 'साफ़ करें'},
    'all': {'en': 'All', 'ar': 'الكل', 'ur': 'تمام', 'hi': 'सभी'},
    'apply_filters': {
      'en': 'Apply filters',
      'ar': 'تطبيق عوامل التصفية',
      'ur': 'فلٹرز لگائیں',
      'hi': 'फ़िल्टर लागू करें',
    },
    'load_more': {
      'en': 'Load more projects',
      'ar': 'تحميل المزيد من المشاريع',
      'ur': 'مزید پراجیکٹس لوڈ کریں',
      'hi': 'और प्रोजेक्ट लोड करें',
    },
    'loading_more': {
      'en': 'Loading projects…',
      'ar': 'جارٍ تحميل المشاريع…',
      'ur': 'پراجیکٹس لوڈ ہو رہے ہیں…',
      'hi': 'प्रोजेक्ट लोड हो रहे हैं…',
    },
    'load_more_failed': {
      'en':
          'More projects could not be loaded. Your current results are unchanged.',
      'ar': 'تعذر تحميل المزيد من المشاريع. لم تتغير النتائج الحالية.',
      'ur': 'مزید پراجیکٹس لوڈ نہیں ہو سکے۔ موجودہ نتائج برقرار ہیں۔',
      'hi': 'और प्रोजेक्ट लोड नहीं हुए। मौजूदा परिणाम सुरक्षित हैं।',
    },
    'retry': {
      'en': 'Try again',
      'ar': 'حاول مرة أخرى',
      'ur': 'دوبارہ کوشش کریں',
      'hi': 'फिर प्रयास करें',
    },
    'no_projects': {
      'en': 'No authorized project Accounts',
      'ar': 'لا توجد حسابات مشاريع مصرح بها',
      'ur': 'کوئی مجاز پراجیکٹ اکاؤنٹس نہیں',
      'hi': 'कोई अधिकृत प्रोजेक्ट अकाउंट्स नहीं',
    },
    'no_results': {
      'en': 'No projects match these filters',
      'ar': 'لا توجد مشاريع تطابق عوامل التصفية',
      'ur': 'کوئی پراجیکٹ ان فلٹرز سے میل نہیں کھاتا',
      'hi': 'इन फ़िल्टर से कोई प्रोजेक्ट मेल नहीं खाता',
    },
    'offline': {
      'en': 'Accounts is unavailable offline',
      'ar': 'الحسابات غير متاحة دون اتصال',
      'ur': 'اکاؤنٹس آف لائن دستیاب نہیں',
      'hi': 'अकाउंट्स ऑफ़लाइन उपलब्ध नहीं है',
    },
    'forbidden': {
      'en': 'Commercial access is not available for this account',
      'ar': 'الوصول التجاري غير متاح لهذا الحساب',
      'ur': 'اس اکاؤنٹ کے لیے کمرشل رسائی دستیاب نہیں',
      'hi': 'इस खाते के लिए कमर्शियल एक्सेस उपलब्ध नहीं है',
    },
    'load_failed': {
      'en': 'Accounts could not be loaded',
      'ar': 'تعذر تحميل الحسابات',
      'ur': 'اکاؤنٹس لوڈ نہیں ہو سکے',
      'hi': 'अकाउंट्स लोड नहीं हो सके',
    },
    'latest_activity': {
      'en': 'Latest commercial activity',
      'ar': 'أحدث نشاط تجاري',
      'ur': 'تازہ ترین کمرشل سرگرمی',
      'hi': 'नवीनतम कमर्शियल गतिविधि',
    },
    'project': {
      'en': 'Project',
      'ar': 'المشروع',
      'ur': 'پراجیکٹ',
      'hi': 'प्रोजेक्ट',
    },
    'client': {'en': 'Client', 'ar': 'العميل', 'ur': 'کلائنٹ', 'hi': 'क्लाइंट'},
    'progress': {
      'en': 'Progress',
      'ar': 'التقدم',
      'ur': 'پیشرفت',
      'hi': 'प्रगति',
    },
    'next_action': {
      'en': 'Next Action',
      'ar': 'الإجراء التالي',
      'ur': 'اگلا اقدام',
      'hi': 'अगली कार्रवाई',
    },
    'building_position': {
      'en': 'Building position',
      'ar': 'وضع المباني',
      'ur': 'بلڈنگ پوزیشن',
      'hi': 'बिल्डिंग स्थिति',
    },
    'recent_invoices': {
      'en': 'Recent claims & invoices',
      'ar': 'أحدث المطالبات والفواتير',
      'ur': 'حالیہ کلیمز اور انوائسز',
      'hi': 'हाल के क्लेम और इनवॉइस',
    },
    'no_records': {
      'en': 'No records yet',
      'ar': 'لا توجد سجلات بعد',
      'ur': 'ابھی کوئی ریکارڈ نہیں',
      'hi': 'अभी कोई रिकॉर्ड नहीं',
    },
    'role_guidance': {
      'en': 'Only actions and values permitted for your role are shown.',
      'ar': 'تظهر فقط الإجراءات والقيم المسموح بها لدورك.',
      'ur': 'صرف آپ کے کردار کے لیے مجاز اعمال اور اقدار دکھائی جاتی ہیں۔',
      'hi': 'केवल आपकी भूमिका के लिए अनुमत कार्रवाई और मान दिखाए जाते हैं।',
    },
    'open_action': {
      'en': 'Open action',
      'ar': 'فتح الإجراء',
      'ur': 'اقدام کھولیں',
      'hi': 'कार्रवाई खोलें',
    },
    'no_action': {
      'en': 'No action',
      'ar': 'لا يوجد إجراء',
      'ur': 'کوئی اقدام نہیں',
      'hi': 'कोई कार्रवाई नहीं',
    },
    'progress_action': {
      'en': 'Billing progress action',
      'ar': 'إجراء تقدم الفوترة',
      'ur': 'بلنگ پیشرفت کا اقدام',
      'hi': 'बिलिंग प्रगति कार्रवाई',
    },
    'action': {
      'en': 'Action',
      'ar': 'الإجراء',
      'ur': 'اقدام',
      'hi': 'कार्रवाई',
    },
    'suggest_progress': {
      'en': 'Suggest progress',
      'ar': 'اقتراح التقدم',
      'ur': 'پیشرفت تجویز کریں',
      'hi': 'प्रगति सुझाएं',
    },
    'confirm_progress': {
      'en': 'Confirm progress',
      'ar': 'تأكيد التقدم',
      'ur': 'پیشرفت کی تصدیق کریں',
      'hi': 'प्रगति की पुष्टि करें',
    },
    'approve_review': {
      'en': 'Approve review',
      'ar': 'اعتماد المراجعة',
      'ur': 'جائزہ منظور کریں',
      'hi': 'समीक्षा स्वीकृत करें',
    },
    'return_for_changes': {
      'en': 'Return for changes',
      'ar': 'إعادة للتعديل',
      'ur': 'تبدیلیوں کے لیے واپس کریں',
      'hi': 'बदलाव के लिए लौटाएं',
    },
    'percentage': {
      'en': 'Percentage',
      'ar': 'النسبة المئوية',
      'ur': 'فیصد',
      'hi': 'प्रतिशत',
    },
    'invalid_percentage': {
      'en': 'Enter a percentage from 0 to 100.',
      'ar': 'أدخل نسبة من 0 إلى 100.',
      'ur': '0 سے 100 تک فیصد درج کریں۔',
      'hi': '0 से 100 तक प्रतिशत दर्ज करें।',
    },
    'evidence_summary': {
      'en': 'Evidence summary',
      'ar': 'ملخص الأدلة',
      'ur': 'ثبوت کا خلاصہ',
      'hi': 'साक्ष्य सारांश',
    },
    'evidence_helper': {
      'en': 'Describe the site evidence supporting this percentage.',
      'ar': 'صف دليل الموقع الذي يدعم هذه النسبة.',
      'ur': 'اس فیصد کی تائید کرنے والے سائٹ ثبوت کی وضاحت کریں۔',
      'hi': 'इस प्रतिशत के समर्थन में साइट साक्ष्य लिखें।',
    },
    'document_references': {
      'en': 'Evidence document IDs',
      'ar': 'معرّفات مستندات الأدلة',
      'ur': 'ثبوت دستاویز کی IDs',
      'hi': 'साक्ष्य दस्तावेज़ ID',
    },
    'document_ids_helper': {
      'en': 'Optional comma-separated current document IDs.',
      'ar': 'معرّفات المستندات الحالية مفصولة بفواصل، اختيارية.',
      'ur': 'اختیاری موجودہ دستاویز IDs، کوما سے جدا۔',
      'hi': 'वैकल्पिक वर्तमान दस्तावेज़ ID, कॉमा से अलग।',
    },
    'reason': {'en': 'Reason', 'ar': 'السبب', 'ur': 'وجہ', 'hi': 'कारण'},
    'reason_required': {
      'en': 'A reason is required.',
      'ar': 'السبب مطلوب.',
      'ur': 'وجہ درکار ہے۔',
      'hi': 'कारण आवश्यक है।',
    },
    'no_available_action': {
      'en': 'No action is available for your current role and this row state.',
      'ar': 'لا يتوفر إجراء لدورك الحالي وحالة هذا الصف.',
      'ur':
          'آپ کے موجودہ کردار اور اس قطار کی حالت کے لیے کوئی اقدام دستیاب نہیں۔',
      'hi':
          'आपकी वर्तमान भूमिका और इस पंक्ति की स्थिति के लिए कोई कार्रवाई उपलब्ध नहीं है।',
    },
    'close': {'en': 'Close', 'ar': 'إغلاق', 'ur': 'بند کریں', 'hi': 'बंद करें'},
    'cancel': {
      'en': 'Cancel',
      'ar': 'إلغاء',
      'ur': 'منسوخ کریں',
      'hi': 'रद्द करें',
    },
    'stale_conflict': {
      'en': 'This record changed. Review the refreshed values and try again.',
      'ar': 'تم تغيير هذا السجل. راجع القيم المحدثة وحاول مرة أخرى.',
      'ur': 'یہ ریکارڈ تبدیل ہو گیا ہے۔ تازہ اقدار دیکھ کر دوبارہ کوشش کریں۔',
      'hi': 'यह रिकॉर्ड बदल गया है। नए मान देखकर फिर प्रयास करें।',
    },
    'uncertain_commit': {
      'en':
          'Confirmation was interrupted. Refresh before retrying; the command may have completed.',
      'ar': 'انقطع التأكيد. حدّث قبل إعادة المحاولة؛ ربما اكتمل الأمر.',
      'ur':
          'تصدیق منقطع ہوئی۔ دوبارہ کوشش سے پہلے ریفریش کریں؛ حکم مکمل ہو چکا ہو سکتا ہے۔',
      'hi':
          'पुष्टि बाधित हुई। दोबारा प्रयास से पहले रीफ़्रेश करें; आदेश पूरा हो सकता है।',
    },
    'session_expired': {
      'en': 'Your session expired. Sign in again before continuing.',
      'ar': 'انتهت جلستك. سجّل الدخول مرة أخرى للمتابعة.',
      'ur': 'آپ کا سیشن ختم ہو گیا۔ جاری رکھنے سے پہلے دوبارہ سائن ان کریں۔',
      'hi': 'आपका सत्र समाप्त हो गया। जारी रखने से पहले फिर साइन इन करें।',
    },
    'action_failed': {
      'en':
          'The action could not be confirmed. Review the fields and try again.',
      'ar': 'تعذر تأكيد الإجراء. راجع الحقول وحاول مرة أخرى.',
      'ur': 'اقدام کی تصدیق نہیں ہو سکی۔ فیلڈز دیکھ کر دوبارہ کوشش کریں۔',
      'hi': 'कार्रवाई की पुष्टि नहीं हुई। फ़ील्ड जांचकर फिर प्रयास करें।',
    },
    'prepare_claim': {'en': 'Prepare client claim'},
    'edit_claim': {'en': 'Edit claim draft'},
    'claim_cap_guidance': {
      'en':
          'Select confirmed lines and keep each amount within the server-authorized Available to Claim cap.',
    },
    'save_draft': {'en': 'Save draft'},
    'claim_identity': {'en': 'Claim identity'},
    'claim_reference': {'en': 'Claim reference'},
    'period_start': {'en': 'Period start'},
    'period_end': {'en': 'Period end'},
    'date_format': {'en': 'YYYY-MM-DD'},
    'claim_lines': {'en': 'Claim lines'},
    'no_claimable_lines': {
      'en': 'No confirmed, reviewed value is currently available to claim.',
    },
    'notes': {'en': 'Notes'},
    'claim_line_required': {'en': 'Select at least one claim line.'},
    'invalid_amount': {
      'en': 'Enter a positive amount with no more than two decimal places.',
    },
    'claim_amount_exceeds_available': {
      'en': 'A claim line exceeds its current Available to Claim cap.',
    },
    'claim_amount': {'en': 'Claim amount (ex VAT)'},
    'evidence_reference': {'en': 'Evidence reference'},
    'previously_claimed': {'en': 'Previously claimed'},
    'claim_detail': {'en': 'Claim detail'},
    'status': {'en': 'Status'},
    'no_evidence': {'en': 'No evidence reference'},
    'send_to_accounts': {'en': 'Send to Accounts'},
    'delete_draft': {'en': 'Delete draft'},
    'create_invoice': {'en': 'Create client invoice'},
    'cancel_claim': {'en': 'Cancel claim'},
    'edit_invoice': {'en': 'Edit invoice draft'},
    'invoice_reference': {'en': 'Invoice reference'},
    'invoice_detail': {'en': 'Client invoice detail'},
    'submit_invoice': {'en': 'Submit client invoice'},
    'start_certification': {'en': 'Start certification review'},
    'record_certification': {'en': 'Record certification'},
    'record_payment': {'en': 'Record client payment'},
    'reverse_payment': {'en': 'Reverse payment'},
    'record_pdc': {'en': 'Record PDC'},
    'update_pdc': {'en': 'Update PDC status'},
    'replace_pdc': {'en': 'Replace PDC'},
    'return_invoice': {'en': 'Return invoice'},
    'cancel_invoice': {'en': 'Cancel invoice'},
    'payment_to_reverse': {'en': 'Payment to reverse'},
    'new_status': {'en': 'New status'},
    'date': {'en': 'Date'},
    'amount': {'en': 'Amount'},
    'certification_reference': {'en': 'Certification reference'},
    'payment_reference': {'en': 'Payment reference'},
    'cheque_number': {'en': 'Cheque number'},
    'reference': {'en': 'Reference'},
    'payment_method': {'en': 'Payment method'},
    'bank_name': {'en': 'Bank name'},
    'current_position': {'en': 'Current position'},
    'not_submitted': {'en': 'Not submitted'},
    'field_required': {'en': 'This field is required.'},
    'invalid_date': {'en': 'Enter a valid calendar date as YYYY-MM-DD.'},
    'confirm': {'en': 'Confirm'},
    'review_invalid_fields': {
      'en': 'Review the highlighted fields before continuing.',
      'ar': 'راجع الحقول المميزة قبل المتابعة.',
      'ur': 'جاری رکھنے سے پہلے نمایاں فیلڈز کا جائزہ لیں۔',
      'hi': 'जारी रखने से पहले चिह्नित फ़ील्ड देखें।',
    },
    'new_supplier_bill': {
      'en': 'New supplier bill',
      'ar': 'فاتورة مورد جديدة',
      'ur': 'نیا سپلائر بل',
      'hi': 'नया सप्लायर बिल',
    },
    'edit_supplier_bill': {
      'en': 'Edit supplier bill',
      'ar': 'تعديل فاتورة المورد',
      'ur': 'سپلائر بل میں ترمیم',
      'hi': 'सप्लायर बिल संपादित करें',
    },
    'three_way_match_guidance': {
      'en':
          'Connect the PO/LPO, accepted delivery and supplier invoice evidence.',
      'ar': 'اربط أمر الشراء والتسليم المقبول ودليل فاتورة المورد.',
      'ur': 'PO/LPO، منظور شدہ ڈیلیوری اور سپلائر انوائس ثبوت منسلک کریں۔',
      'hi': 'PO/LPO, स्वीकृत डिलीवरी और सप्लायर इनवॉइस साक्ष्य जोड़ें।',
    },
    'supplier_invoice': {
      'en': 'Supplier invoice',
      'ar': 'فاتورة المورد',
      'ur': 'سپلائر انوائس',
      'hi': 'सप्लायर इनवॉइस',
    },
    'supplier_name': {
      'en': 'Supplier name',
      'ar': 'اسم المورد',
      'ur': 'سپلائر کا نام',
      'hi': 'सप्लायर का नाम',
    },
    'supplier_invoice_reference': {
      'en': 'Supplier invoice reference',
      'ar': 'مرجع فاتورة المورد',
      'ur': 'سپلائر انوائس حوالہ',
      'hi': 'सप्लायर इनवॉइस संदर्भ',
    },
    'invoice_date': {
      'en': 'Invoice date',
      'ar': 'تاريخ الفاتورة',
      'ur': 'انوائس کی تاریخ',
      'hi': 'इनवॉइस तिथि',
    },
    'due_date': {
      'en': 'Due date',
      'ar': 'تاريخ الاستحقاق',
      'ur': 'واجب الادا تاریخ',
      'hi': 'देय तिथि',
    },
    'ex_vat': {
      'en': 'Amount excluding VAT',
      'ar': 'المبلغ قبل الضريبة',
      'ur': 'VAT کے بغیر رقم',
      'hi': 'VAT रहित राशि',
    },
    'vat_rate': {
      'en': 'VAT rate',
      'ar': 'نسبة ضريبة القيمة المضافة',
      'ur': 'VAT شرح',
      'hi': 'VAT दर',
    },
    'three_way_match': {
      'en': 'Three-way match',
      'ar': 'المطابقة الثلاثية',
      'ur': 'تین طرفہ میچ',
      'hi': 'तीन-तरफ़ा मिलान',
    },
    'po_lpo': {
      'en': 'PO / LPO',
      'ar': 'أمر الشراء / أمر الشراء المحلي',
      'ur': 'PO / LPO',
      'hi': 'PO / LPO',
    },
    'po_lpo_reference': {
      'en': 'PO / LPO reference',
      'ar': 'مرجع أمر الشراء',
      'ur': 'PO / LPO حوالہ',
      'hi': 'PO / LPO संदर्भ',
    },
    'current_document_id': {
      'en': 'Current document ID',
      'ar': 'معرّف المستند الحالي',
      'ur': 'موجودہ دستاویز ID',
      'hi': 'वर्तमान दस्तावेज़ ID',
    },
    'accepted_delivery': {
      'en': 'Accepted delivery',
      'ar': 'التسليم المقبول',
      'ur': 'منظور شدہ ڈیلیوری',
      'hi': 'स्वीकृत डिलीवरी',
    },
    'receipt_review_id': {
      'en': 'Confirmed receipt review ID',
      'ar': 'معرّف مراجعة الاستلام المؤكدة',
      'ur': 'تصدیق شدہ رسید جائزہ ID',
      'hi': 'पुष्ट रसीद समीक्षा ID',
    },
    'trusted_receipt_helper': {
      'en':
          'Only a confirmed receipt with a positive good quantity is accepted.',
      'ar': 'يُقبل فقط استلام مؤكد بكمية سليمة موجبة.',
      'ur': 'صرف مثبت اچھی مقدار والی تصدیق شدہ رسید قبول ہوتی ہے۔',
      'hi': 'केवल सकारात्मक अच्छी मात्रा वाली पुष्ट रसीद स्वीकार होती है।',
    },
    'mismatch_reason': {
      'en': 'Mismatch reason',
      'ar': 'سبب عدم المطابقة',
      'ur': 'عدم مطابقت کی وجہ',
      'hi': 'अमिलान का कारण',
    },
    'supplier_bill_detail': {
      'en': 'Supplier bill detail',
      'ar': 'تفاصيل فاتورة المورد',
      'ur': 'سپلائر بل کی تفصیل',
      'hi': 'सप्लायर बिल विवरण',
    },
    'approve_supplier_bill': {
      'en': 'Approve supplier bill',
      'ar': 'اعتماد فاتورة المورد',
      'ur': 'سپلائر بل منظور کریں',
      'hi': 'सप्लायर बिल स्वीकृत करें',
    },
    'record_supplier_payment': {
      'en': 'Record supplier payment',
      'ar': 'تسجيل دفعة المورد',
      'ur': 'سپلائر ادائیگی ریکارڈ کریں',
      'hi': 'सप्लायर भुगतान दर्ज करें',
    },
    'cancel_supplier_bill': {
      'en': 'Cancel supplier bill',
      'ar': 'إلغاء فاتورة المورد',
      'ur': 'سپلائر بل منسوخ کریں',
      'hi': 'सप्लायर बिल रद्द करें',
    },
    'admin_exception_reason': {
      'en': 'Admin exception reason',
      'ar': 'سبب استثناء المسؤول',
      'ur': 'ایڈمن استثنا کی وجہ',
      'hi': 'एडमिन अपवाद का कारण',
    },
    'admin_exception_helper': {
      'en':
          'Required for every unmatched Admin approval; the supplier invoice document remains mandatory.',
      'ar':
          'مطلوب لكل اعتماد غير مطابق من المسؤول؛ وتبقى وثيقة فاتورة المورد إلزامية.',
      'ur':
          'ہر غیر مماثل ایڈمن منظوری کے لیے ضروری؛ سپلائر انوائس دستاویز پھر بھی لازمی ہے۔',
      'hi':
          'हर अमिलान एडमिन स्वीकृति के लिए आवश्यक; सप्लायर इनवॉइस दस्तावेज़ अनिवार्य रहता है।',
    },
    'missing_evidence': {
      'en': 'Missing evidence',
      'ar': 'دليل مفقود',
      'ur': 'ثبوت غائب ہے',
      'hi': 'साक्ष्य अनुपस्थित',
    },
    'match_status': {
      'en': 'Match status',
      'ar': 'حالة المطابقة',
      'ur': 'میچ کی حالت',
      'hi': 'मिलान स्थिति',
    },
    'payment_status': {
      'en': 'Payment status',
      'ar': 'حالة الدفع',
      'ur': 'ادائیگی کی حالت',
      'hi': 'भुगतान स्थिति',
    },
    'set_commercial_baseline': {
      'en': 'Set commercial baseline',
      'ar': 'إعداد خط الأساس التجاري',
      'ur': 'کمرشل بیس لائن مقرر کریں',
      'hi': 'कमर्शियल बेसलाइन सेट करें',
    },
    'revise_commercial_baseline': {
      'en': 'Revise commercial baseline',
      'ar': 'مراجعة خط الأساس التجاري',
      'ur': 'کمرشل بیس لائن پر نظر ثانی',
      'hi': 'कमर्शियल बेसलाइन संशोधित करें',
    },
    'baseline_editor_guidance': {
      'en':
          'Protect the contract snapshot, physical-building allocation, billing stages and review policy in one audited revision.',
      'ar':
          'احمِ لقطة العقد وتوزيع المباني الفعلية ومراحل الفوترة وسياسة المراجعة ضمن مراجعة مدققة واحدة.',
      'ur':
          'کنٹریکٹ اسنیپ شاٹ، فزیکل بلڈنگ تقسیم، بلنگ مراحل اور جائزہ پالیسی کو ایک آڈٹ شدہ ریویژن میں محفوظ کریں۔',
      'hi':
          'कॉन्ट्रैक्ट स्नैपशॉट, भौतिक भवन आवंटन, बिलिंग चरण और समीक्षा नीति को एक ऑडिटेड संशोधन में सुरक्षित करें।',
    },
    'commercial_terms': {
      'en': 'Commercial terms',
      'ar': 'الشروط التجارية',
      'ur': 'کمرشل شرائط',
      'hi': 'कमर्शियल शर्तें',
    },
    'contract_value': {
      'en': 'Contract value',
      'ar': 'قيمة العقد',
      'ur': 'کنٹریکٹ ویلیو',
      'hi': 'कॉन्ट्रैक्ट मूल्य',
    },
    'currency': {
      'en': 'Currency',
      'ar': 'العملة',
      'ur': 'کرنسی',
      'hi': 'मुद्रा',
    },
    'invalid_currency': {
      'en': 'Enter a three-letter currency code.',
      'ar': 'أدخل رمز عملة من ثلاثة أحرف.',
      'ur': 'تین حرفی کرنسی کوڈ درج کریں۔',
      'hi': 'तीन अक्षर का मुद्रा कोड दर्ज करें।',
    },
    'payment_terms_days': {
      'en': 'Payment terms (days)',
      'ar': 'مدة السداد (أيام)',
      'ur': 'ادائیگی کی مدت (دن)',
      'hi': 'भुगतान अवधि (दिन)',
    },
    'reminder_lead_days': {
      'en': 'Reminder lead (days)',
      'ar': 'مهلة التذكير (أيام)',
      'ur': 'یاد دہانی کی پیشگی مدت (دن)',
      'hi': 'रिमाइंडर अग्रिम अवधि (दिन)',
    },
    'physical_building_allocations': {
      'en': 'Physical building allocations',
      'ar': 'توزيعات المباني الفعلية',
      'ur': 'فزیکل بلڈنگ تقسیم',
      'hi': 'भौतिक भवन आवंटन',
    },
    'common_scope_excluded': {
      'en':
          'Common / All Buildings is excluded by policy. Physical allocations must total exactly 100%.',
      'ar':
          'النطاق العام / كل المباني مستبعد حسب السياسة. يجب أن يساوي مجموع التوزيعات الفعلية 100٪ تماماً.',
      'ur':
          'Common / All Buildings پالیسی کے تحت خارج ہے۔ فزیکل تقسیم کا مجموعہ بالکل 100% ہونا چاہیے۔',
      'hi':
          'Common / All Buildings नीति के अनुसार बाहर है। भौतिक आवंटन कुल ठीक 100% होना चाहिए।',
    },
    'no_physical_buildings': {
      'en':
          'Add at least one active physical building before setting a commercial baseline.',
      'ar':
          'أضف مبنى فعلياً نشطاً واحداً على الأقل قبل إعداد خط الأساس التجاري.',
      'ur':
          'کمرشل بیس لائن مقرر کرنے سے پہلے کم از کم ایک فعال فزیکل بلڈنگ شامل کریں۔',
      'hi':
          'कमर्शियल बेसलाइन सेट करने से पहले कम से कम एक सक्रिय भौतिक भवन जोड़ें।',
    },
    'building_total': {
      'en': 'Building allocation total',
      'ar': 'إجمالي توزيع المباني',
      'ur': 'بلڈنگ تقسیم کا مجموعہ',
      'hi': 'भवन आवंटन कुल',
    },
    'billing_stage_allocations': {
      'en': 'Billing stage allocations',
      'ar': 'توزيعات مراحل الفوترة',
      'ur': 'بلنگ مرحلہ تقسیم',
      'hi': 'बिलिंग चरण आवंटन',
    },
    'stage_total': {
      'en': 'Stage allocation total',
      'ar': 'إجمالي توزيع المراحل',
      'ur': 'مرحلہ تقسیم کا مجموعہ',
      'hi': 'चरण आवंटन कुल',
    },
    'management_review_policy': {
      'en': 'Management review policy',
      'ar': 'سياسة مراجعة الإدارة',
      'ur': 'مینجمنٹ جائزہ پالیسی',
      'hi': 'प्रबंधन समीक्षा नीति',
    },
    'always_require_review': {
      'en': 'Always require management review',
      'ar': 'طلب مراجعة الإدارة دائماً',
      'ur': 'ہمیشہ مینجمنٹ جائزہ درکار ہو',
      'hi': 'हमेशा प्रबंधन समीक्षा आवश्यक करें',
    },
    'review_threshold_optional': {
      'en': 'Review threshold amount (optional)',
      'ar': 'مبلغ حد المراجعة (اختياري)',
      'ur': 'جائزہ حد رقم (اختیاری)',
      'hi': 'समीक्षा सीमा राशि (वैकल्पिक)',
    },
    'review_roles': {
      'en': 'Reviewing exact roles',
      'ar': 'الأدوار الدقيقة للمراجعة',
      'ur': 'جائزہ لینے والے درست کردار',
      'hi': 'समीक्षा करने वाली सटीक भूमिकाएँ',
    },
    'invalid_whole_number': {
      'en': 'Enter a valid whole number.',
      'ar': 'أدخل عدداً صحيحاً صالحاً.',
      'ur': 'درست مکمل عدد درج کریں۔',
      'hi': 'मान्य पूर्ण संख्या दर्ज करें।',
    },
    'allocation_validation_failed': {
      'en':
          'Building and stage allocations must be positive, unique and total exactly 100%. Reminder lead cannot exceed payment terms.',
      'ar':
          'يجب أن تكون توزيعات المباني والمراحل موجبة وفريدة ومجموعها 100٪ تماماً. لا يجوز أن تتجاوز مهلة التذكير مدة السداد.',
      'ur':
          'بلڈنگ اور مرحلہ تقسیم مثبت، منفرد اور بالکل 100% ہونی چاہیے۔ یاد دہانی کی مدت ادائیگی مدت سے زیادہ نہیں ہو سکتی۔',
      'hi':
          'भवन और चरण आवंटन सकारात्मक, अद्वितीय और कुल ठीक 100% होना चाहिए। रिमाइंडर अवधि भुगतान अवधि से अधिक नहीं हो सकती।',
    },
    'confirm_baseline': {
      'en': 'Activate commercial baseline?',
      'ar': 'تفعيل خط الأساس التجاري؟',
      'ur': 'کمرشل بیس لائن فعال کریں؟',
      'hi': 'कमर्शियल बेसलाइन सक्रिय करें?',
    },
    'confirm_baseline_revision': {
      'en': 'Create a new baseline revision?',
      'ar': 'إنشاء مراجعة جديدة لخط الأساس؟',
      'ur': 'نیا بیس لائن ریویژن بنائیں؟',
      'hi': 'नया बेसलाइन संशोधन बनाएँ?',
    },
    'baseline_confirmation_body': {
      'en':
          'This creates an immutable audited snapshot. Existing claims and invoices are never rewritten.',
      'ar':
          'سيؤدي هذا إلى إنشاء لقطة ثابتة ومدققة. لن تُعاد كتابة المطالبات والفواتير الحالية.',
      'ur':
          'یہ ایک ناقابل تبدیلی آڈٹ شدہ اسنیپ شاٹ بناتا ہے۔ موجودہ کلیمز اور انوائسز دوبارہ نہیں لکھے جاتے۔',
      'hi':
          'यह एक अपरिवर्तनीय ऑडिटेड स्नैपशॉट बनाता है। मौजूदा क्लेम और इनवॉइस दोबारा नहीं लिखे जाते।',
    },
    'activate_baseline': {
      'en': 'Activate baseline',
      'ar': 'تفعيل خط الأساس',
      'ur': 'بیس لائن فعال کریں',
      'hi': 'बेसलाइन सक्रिय करें',
    },
    'save_revision': {
      'en': 'Save new revision',
      'ar': 'حفظ المراجعة الجديدة',
      'ur': 'نیا ریویژن محفوظ کریں',
      'hi': 'नया संशोधन सहेजें',
    },
    'recent_claims': {
      'en': 'Recent claims',
      'ar': 'أحدث المطالبات',
      'ur': 'حالیہ کلیمز',
      'hi': 'हाल के क्लेम',
    },
    'role_project_engineer': {
      'en': 'Project Engineer',
      'ar': 'مهندس المشروع',
      'ur': 'پراجیکٹ انجینئر',
      'hi': 'प्रोजेक्ट इंजीनियर',
    },
    'role_senior_mechanical_engineer': {
      'en': 'Senior Mechanical Engineer',
      'ar': 'مهندس ميكانيكي أول',
      'ur': 'سینئر مکینیکل انجینئر',
      'hi': 'सीनियर मैकेनिकल इंजीनियर',
    },
    'role_project_manager': {
      'en': 'Project Manager',
      'ar': 'مدير المشروع',
      'ur': 'پراجیکٹ مینیجر',
      'hi': 'प्रोजेक्ट मैनेजर',
    },
    'role_workshop_in_charge': {
      'en': 'Workshop In-Charge',
      'ar': 'مسؤول الورشة',
      'ur': 'ورکشاپ انچارج',
      'hi': 'वर्कशॉप प्रभारी',
    },
    'role_document_controller': {
      'en': 'Document Controller',
      'ar': 'مراقب المستندات',
      'ur': 'دستاویز کنٹرولر',
      'hi': 'दस्तावेज़ नियंत्रक',
    },
    'building': {'en': 'Building', 'ar': 'المبنى', 'ur': 'بلڈنگ', 'hi': 'भवन'},
    'stage': {
      'en': 'Billing stage',
      'ar': 'مرحلة الفوترة',
      'ur': 'بلنگ مرحلہ',
      'hi': 'बिलिंग चरण',
    },
    'suggested': {
      'en': 'Site suggested',
      'ar': 'اقتراح الموقع',
      'ur': 'سائٹ تجویز',
      'hi': 'साइट सुझाव',
    },
    'review': {
      'en': 'Management review',
      'ar': 'مراجعة الإدارة',
      'ur': 'مینجمنٹ جائزہ',
      'hi': 'प्रबंधन समीक्षा',
    },
    'owner_evidence': {
      'en': 'Owner / Evidence',
      'ar': 'المسؤول / الدليل',
      'ur': 'ذمہ دار / ثبوت',
      'hi': 'जिम्मेदार / साक्ष्य',
    },
    'action_owner': {
      'en': 'Action owner',
      'ar': 'مسؤول الإجراء',
      'ur': 'اقدام کا ذمہ دار',
      'hi': 'कार्रवाई जिम्मेदार',
    },
    'evidence': {
      'en': 'Evidence',
      'ar': 'الدليل',
      'ur': 'ثبوت',
      'hi': 'साक्ष्य',
    },
    'with_evidence': {
      'en': 'With evidence',
      'ar': 'مع دليل',
      'ur': 'ثبوت کے ساتھ',
      'hi': 'साक्ष्य सहित',
    },
    'without_evidence': {
      'en': 'Without evidence',
      'ar': 'بدون دليل',
      'ur': 'ثبوت کے بغیر',
      'hi': 'साक्ष्य रहित',
    },
    'owner_site_engineer': {
      'en': 'Site Engineer',
      'ar': 'مهندس الموقع',
      'ur': 'سائٹ انجینئر',
      'hi': 'साइट इंजीनियर',
    },
    'owner_project_engineer': {
      'en': 'Project Engineer',
      'ar': 'مهندس المشروع',
      'ur': 'پراجیکٹ انجینئر',
      'hi': 'प्रोजेक्ट इंजीनियर',
    },
    'owner_management': {
      'en': 'Management review',
      'ar': 'مراجعة الإدارة',
      'ur': 'مینجمنٹ جائزہ',
      'hi': 'प्रबंधन समीक्षा',
    },
    'no_progress_results': {
      'en': 'No billing progress rows match these filters',
      'ar': 'لا توجد صفوف تقدم فوترة تطابق عوامل التصفية',
      'ur': 'کوئی بلنگ پیشرفت قطار ان فلٹرز سے میل نہیں کھاتی',
      'hi': 'कोई बिलिंग प्रगति पंक्ति इन फ़िल्टर से मेल नहीं खाती',
    },
    'contract_baseline': {
      'en': 'Contract Value',
      'ar': 'قيمة العقد',
      'ur': 'کنٹریکٹ ویلیو',
      'hi': 'अनुबंध मूल्य',
    },
    'cumulative_eligible': {
      'en': 'Cumulative Eligible',
      'ar': 'المؤهل التراكمي',
      'ur': 'مجموعی اہل رقم',
      'hi': 'संचयी पात्र',
    },
    'already_claimed': {
      'en': 'Already Claimed',
      'ar': 'تمت المطالبة به',
      'ur': 'پہلے کلیم شدہ',
      'hi': 'पहले दावा किया',
    },
    'stage_value': {
      'en': 'Stage Value',
      'ar': 'قيمة المرحلة',
      'ur': 'مرحلے کی قیمت',
      'hi': 'चरण मूल्य',
    },
    'eligible_amount': {
      'en': 'Eligible Amount',
      'ar': 'المبلغ المؤهل',
      'ur': 'اہل رقم',
      'hi': 'पात्र राशि',
    },
    'last_update': {
      'en': 'Last Update',
      'ar': 'آخر تحديث',
      'ur': 'آخری اپ ڈیٹ',
      'hi': 'अंतिम अपडेट',
    },
    'claim_status': {
      'en': 'Claim status',
      'ar': 'حالة المطالبة',
      'ur': 'کلیم کی حالت',
      'hi': 'दावे की स्थिति',
    },
    'invoice_status': {
      'en': 'Invoice status',
      'ar': 'حالة الفاتورة',
      'ur': 'انوائس کی حالت',
      'hi': 'इनवॉइस स्थिति',
    },
    'due_state': {
      'en': 'Due state',
      'ar': 'حالة الاستحقاق',
      'ur': 'واجب الادا حالت',
      'hi': 'देय स्थिति',
    },
    'supplier_search': {
      'en': 'Search supplier or invoice reference',
      'ar': 'ابحث عن المورد أو مرجع الفاتورة',
      'ur': 'سپلائر یا انوائس حوالہ تلاش کریں',
      'hi': 'सप्लायर या इनवॉइस संदर्भ खोजें',
    },
    'no_invoice_results': {
      'en': 'No claims or invoices match these filters',
      'ar': 'لا توجد مطالبات أو فواتير تطابق عوامل التصفية',
      'ur': 'کوئی کلیم یا انوائس ان فلٹرز سے میل نہیں کھاتا',
      'hi': 'कोई दावा या इनवॉइस इन फ़िल्टर से मेल नहीं खाता',
    },
    'no_supplier_results': {
      'en': 'No supplier bills match these filters',
      'ar': 'لا توجد فواتير موردين تطابق عوامل التصفية',
      'ur': 'کوئی سپلائر بل ان فلٹرز سے میل نہیں کھاتا',
      'hi': 'कोई सप्लायर बिल इन फ़िल्टर से मेल नहीं खाता',
    },
    'invoice_period': {
      'en': 'Invoice / Period',
      'ar': 'الفاتورة / الفترة',
      'ur': 'انوائس / مدت',
      'hi': 'इनवॉइस / अवधि',
    },
    'claimed_ex_vat': {
      'en': 'Claimed Ex VAT',
      'ar': 'المطالب به دون الضريبة',
      'ur': 'VAT کے بغیر کلیم',
      'hi': 'VAT रहित दावा',
    },
    'certified_ex_vat': {
      'en': 'Certified Ex VAT',
      'ar': 'المعتمد دون الضريبة',
      'ur': 'VAT کے بغیر سرٹیفائیڈ',
      'hi': 'VAT रहित प्रमाणित',
    },
    'total_incl_vat': {
      'en': 'Total Incl. VAT',
      'ar': 'الإجمالي شامل الضريبة',
      'ur': 'VAT سمیت کل',
      'hi': 'VAT सहित कुल',
    },
    'submitted': {
      'en': 'Submitted',
      'ar': 'تاريخ التقديم',
      'ur': 'جمع کرانے کی تاریخ',
      'hi': 'जमा तिथि',
    },
    'due_alert': {
      'en': 'Due / Alert',
      'ar': 'الاستحقاق / التنبيه',
      'ur': 'واجب الادا / الرٹ',
      'hi': 'देय / अलर्ट',
    },
    'payment_pdc': {
      'en': 'Payment / PDC',
      'ar': 'الدفع / الشيك الآجل',
      'ur': 'ادائیگی / PDC',
      'hi': 'भुगतान / PDC',
    },
    'paid_till_date': {
      'en': 'Amount Paid Till Date',
      'ar': 'المبلغ المدفوع حتى تاريخه',
      'ur': 'آج تک ادا شدہ رقم',
      'hi': 'आज तक भुगतान',
    },
    'supplier': {
      'en': 'Supplier',
      'ar': 'المورد',
      'ur': 'سپلائر',
      'hi': 'सप्लायर',
    },
    'vat': {'en': 'VAT', 'ar': 'الضريبة', 'ur': 'VAT', 'hi': 'VAT'},
    'total': {'en': 'Total', 'ar': 'الإجمالي', 'ur': 'کل', 'hi': 'कुल'},
    'invoice_evidence': {
      'en': 'Invoice Evidence',
      'ar': 'دليل الفاتورة',
      'ur': 'انوائس ثبوت',
      'hi': 'इनवॉइस साक्ष्य',
    },
    'evidence_present': {
      'en': 'Present',
      'ar': 'موجود',
      'ur': 'موجود',
      'hi': 'उपलब्ध',
    },
    'status_draft': {
      'en': 'Draft',
      'ar': 'مسودة',
      'ur': 'ڈرافٹ',
      'hi': 'ड्राफ्ट',
    },
    'status_ready_for_accounts': {
      'en': 'Ready for Accounts',
      'ar': 'جاهز للحسابات',
      'ur': 'اکاؤنٹس کے لیے تیار',
      'hi': 'अकाउंट्स के लिए तैयार',
    },
    'status_invoiced': {
      'en': 'Invoiced',
      'ar': 'مفوتر',
      'ur': 'انوائس شدہ',
      'hi': 'इनवॉइस किया',
    },
    'status_cancelled': {
      'en': 'Cancelled',
      'ar': 'ملغى',
      'ur': 'منسوخ',
      'hi': 'रद्द',
    },
    'status_submitted': {
      'en': 'Submitted',
      'ar': 'مقدم',
      'ur': 'جمع شدہ',
      'hi': 'जमा',
    },
    'status_under_certification': {
      'en': 'Under Certification',
      'ar': 'قيد الاعتماد',
      'ur': 'سرٹیفیکیشن کے تحت',
      'hi': 'प्रमाणनाधीन',
    },
    'status_partially_certified': {
      'en': 'Partially Certified',
      'ar': 'معتمد جزئيا',
      'ur': 'جزوی سرٹیفائیڈ',
      'hi': 'आंशिक प्रमाणित',
    },
    'status_certified': {
      'en': 'Certified',
      'ar': 'معتمد',
      'ur': 'سرٹیفائیڈ',
      'hi': 'प्रमाणित',
    },
    'status_partially_paid': {
      'en': 'Partially Paid',
      'ar': 'مدفوع جزئيا',
      'ur': 'جزوی ادا شدہ',
      'hi': 'आंशिक भुगतान',
    },
    'status_paid': {
      'en': 'Paid',
      'ar': 'مدفوع',
      'ur': 'ادا شدہ',
      'hi': 'भुगतान',
    },
    'status_returned': {
      'en': 'Returned',
      'ar': 'مرتجع',
      'ur': 'واپس شدہ',
      'hi': 'लौटाया',
    },
    'status_on_track': {
      'en': 'On Track',
      'ar': 'ضمن المسار',
      'ur': 'درست سمت',
      'hi': 'समय पर',
    },
    'status_due_soon': {
      'en': 'Due Soon',
      'ar': 'مستحق قريبا',
      'ur': 'جلد واجب الادا',
      'hi': 'जल्द देय',
    },
    'status_due_today': {
      'en': 'Due Today',
      'ar': 'مستحق اليوم',
      'ur': 'آج واجب الادا',
      'hi': 'आज देय',
    },
    'status_overdue': {
      'en': 'Overdue',
      'ar': 'متأخر',
      'ur': 'تاخیر شدہ',
      'hi': 'अतिदेय',
    },
    'status_blocked': {
      'en': 'Blocked',
      'ar': 'محظور',
      'ur': 'بلاک شدہ',
      'hi': 'अवरुद्ध',
    },
    'status_review': {
      'en': 'Review',
      'ar': 'مراجعة',
      'ur': 'جائزہ',
      'hi': 'समीक्षा',
    },
    'status_matched': {
      'en': 'Matched',
      'ar': 'مطابق',
      'ur': 'میچ شدہ',
      'hi': 'मिलान',
    },
    'status_pending': {
      'en': 'Pending',
      'ar': 'معلق',
      'ur': 'زیر التوا',
      'hi': 'लंबित',
    },
    'status_approved': {
      'en': 'Approved',
      'ar': 'معتمد',
      'ur': 'منظور',
      'hi': 'स्वीकृत',
    },
  };

  static String text(AppLanguage language, String key) {
    final values = _copy[key];
    if (values == null) return key;
    return values[language.code] ?? values['en'] ?? key;
  }
}
