import 'app_language.dart';

abstract final class YorksV1WorkforceDashboardStrings {
  static const _copy = <String, Map<String, String>>{
    'title': {
      'en': 'Workforce Overview',
      'ar': 'نظرة عامة على القوى العاملة',
      'ur': 'افرادی قوت کا جائزہ',
      'hi': 'कार्यबल अवलोकन',
    },
    'body': {
      'en': 'Server-confirmed attendance, monthly progress and action queues.',
      'ar': 'الحضور المؤكد من الخادم والتقدم الشهري وقوائم الإجراءات.',
      'ur': 'سرور سے تصدیق شدہ حاضری، ماہانہ پیش رفت اور کارروائی کی قطاریں۔',
      'hi': 'सर्वर-पुष्ट उपस्थिति, मासिक प्रगति और कार्रवाई कतारें।',
    },
    'refresh': {
      'en': 'Refresh',
      'ar': 'تحديث',
      'ur': 'تازہ کریں',
      'hi': 'रीफ़्रेश',
    },
    'complete_today_attendance': {
      'en': "Complete Today's Attendance",
      'ar': 'استكمال حضور اليوم',
      'ur': 'آج کی حاضری مکمل کریں',
      'hi': 'आज की उपस्थिति पूरी करें',
    },
    'open_review_queue': {
      'en': 'Review Queue',
      'ar': 'قائمة المراجعة',
      'ur': 'جائزہ قطار',
      'hi': 'समीक्षा कतार',
    },
    'open_final_approval_queue': {
      'en': 'Final Approval Queue',
      'ar': 'قائمة الموافقة النهائية',
      'ur': 'حتمی منظوری کی قطار',
      'hi': 'अंतिम अनुमोदन कतार',
    },
    'open_reopen_queue': {
      'en': 'Reopen Requests',
      'ar': 'طلبات إعادة الفتح',
      'ur': 'دوبارہ کھولنے کی درخواستیں',
      'hi': 'फिर खोलने के अनुरोध',
    },
    'my_team': {
      'en': 'My Team',
      'ar': 'فريقي',
      'ur': 'میری ٹیم',
      'hi': 'मेरी टीम',
    },
    'today_date': {
      'en': "Today's Date",
      'ar': 'تاريخ اليوم',
      'ur': 'آج کی تاریخ',
      'hi': 'आज की तारीख',
    },
    'workers': {
      'en': 'Workers',
      'ar': 'العمال',
      'ur': 'ورکرز',
      'hi': 'कर्मचारी',
    },
    'present': {'en': 'Present', 'ar': 'حاضر', 'ur': 'حاضر', 'hi': 'उपस्थित'},
    'absent': {
      'en': 'Absent',
      'ar': 'غائب',
      'ur': 'غیر حاضر',
      'hi': 'अनुपस्थित',
    },
    'leave': {
      'en': 'On leave',
      'ar': 'في إجازة',
      'ur': 'چھٹی پر',
      'hi': 'अवकाश पर',
    },
    'missing': {
      'en': 'Not entered',
      'ar': 'غير مدخل',
      'ur': 'درج نہیں',
      'hi': 'दर्ज नहीं',
    },
    'today_completion': {
      'en': 'Today completion',
      'ar': 'اكتمال اليوم',
      'ur': 'آج کی تکمیل',
      'hi': 'आज की पूर्णता',
    },
    'month_completion': {
      'en': 'Current Month Completion',
      'ar': 'اكتمال الشهر',
      'ur': 'ماہ کی تکمیل',
      'hi': 'माह की पूर्णता',
    },
    'warnings': {
      'en': 'Warnings',
      'ar': 'تحذيرات',
      'ur': 'انتباہات',
      'hi': 'चेतावनियां',
    },
    'returned': {
      'en': 'Returned Corrections',
      'ar': 'معاد',
      'ur': 'واپس کیے گئے',
      'hi': 'लौटाए गए',
    },
    'active_projects': {
      'en': 'Active Projects',
      'ar': 'المشاريع النشطة',
      'ur': 'فعال منصوبے',
      'hi': 'सक्रिय परियोजनाएं',
    },
    'workers_across_projects': {
      'en': 'Workers Across Projects',
      'ar': 'العمال عبر المشاريع',
      'ur': 'منصوبوں میں ورکرز',
      'hi': 'परियोजनाओं में कर्मचारी',
    },
    'attendance_completion': {
      'en': 'Attendance Completion',
      'ar': 'اكتمال الحضور',
      'ur': 'حاضری کی تکمیل',
      'hi': 'उपस्थिति पूर्णता',
    },
    'awaiting_review': {
      'en': 'Timesheets Awaiting Review',
      'ar': 'سجلات الدوام بانتظار المراجعة',
      'ur': 'جائزے کی منتظر ٹائم شیٹس',
      'hi': 'समीक्षा की प्रतीक्षा में टाइमशीट',
    },
    'awaiting_approval': {
      'en': 'Timesheets Awaiting Approval',
      'ar': 'سجلات الدوام بانتظار الموافقة',
      'ur': 'منظوری کی منتظر ٹائم شیٹس',
      'hi': 'अनुमोदन की प्रतीक्षा में टाइमशीट',
    },
    'missing_attendance': {
      'en': 'Missing Attendance',
      'ar': 'الحضور المفقود',
      'ur': 'غائب حاضری',
      'hi': 'अनुपस्थित प्रविष्टियां',
    },
    'overtime_exceptions': {
      'en': 'Overtime Exceptions',
      'ar': 'استثناءات العمل الإضافي',
      'ur': 'اوور ٹائم استثنا',
      'hi': 'ओवरटाइम अपवाद',
    },
    'returned_periods': {
      'en': 'Returned Periods',
      'ar': 'الفترات المعادة',
      'ur': 'واپس کیے گئے ادوار',
      'hi': 'लौटाई गई अवधियां',
    },
    'active_workers': {
      'en': 'Active Workers',
      'ar': 'العمال النشطون',
      'ur': 'فعال ورکرز',
      'hi': 'सक्रिय कर्मचारी',
    },
    'active_supervisors': {
      'en': 'Active Supervisors',
      'ar': 'المشرفون النشطون',
      'ur': 'فعال سپروائزرز',
      'hi': 'सक्रिय पर्यवेक्षक',
    },
    'attendance_missing_today': {
      'en': 'Attendance Missing Today',
      'ar': 'حضور اليوم مفقود',
      'ur': 'آج کی غائب حاضری',
      'hi': 'आज की अनुपस्थित प्रविष्टियां',
    },
    'monthly_reports_pending': {
      'en': 'Monthly Reports Pending',
      'ar': 'التقارير الشهرية المعلقة',
      'ur': 'زیر التوا ماہانہ رپورٹس',
      'hi': 'लंबित मासिक रिपोर्ट',
    },
    'returned_for_correction': {
      'en': 'Returned for Correction',
      'ar': 'معاد للتصحيح',
      'ur': 'اصلاح کے لیے واپس',
      'hi': 'सुधार हेतु लौटाया गया',
    },
    'awaiting_final_approval': {
      'en': 'Awaiting Final Approval',
      'ar': 'بانتظار الموافقة النهائية',
      'ur': 'حتمی منظوری کا منتظر',
      'hi': 'अंतिम अनुमोदन प्रतीक्षित',
    },
    'locked_periods': {
      'en': 'Locked Periods',
      'ar': 'الفترات المقفلة',
      'ur': 'مقفل ادوار',
      'hi': 'लॉक की गई अवधियां',
    },
    'reopen_requests': {
      'en': 'Reopen Requests',
      'ar': 'طلبات إعادة الفتح',
      'ur': 'دوبارہ کھولنے کی درخواستیں',
      'hi': 'फिर खोलने के अनुरोध',
    },
    'configuration_issues': {
      'en': 'Configuration Issues',
      'ar': 'مشكلات الإعداد',
      'ur': 'کنفیگریشن مسائل',
      'hi': 'कॉन्फ़िगरेशन समस्याएं',
    },
    'pending': {
      'en': 'Monthly pending',
      'ar': 'شهري معلق',
      'ur': 'ماہانہ زیر التوا',
      'hi': 'मासिक लंबित',
    },
    'awaiting_final': {
      'en': 'Awaiting final',
      'ar': 'بانتظار النهائي',
      'ur': 'حتمی منظوری کا منتظر',
      'hi': 'अंतिम प्रतीक्षित',
    },
    'locked': {'en': 'Locked', 'ar': 'مقفل', 'ur': 'مقفل', 'hi': 'लॉक'},
    'reopen': {
      'en': 'Reopen requests',
      'ar': 'طلبات إعادة الفتح',
      'ur': 'دوبارہ کھولنے کی درخواستیں',
      'hi': 'फिर खोलने के अनुरोध',
    },
    'configuration': {
      'en': 'Configuration issues',
      'ar': 'مشكلات الإعداد',
      'ur': 'کنفیگریشن مسائل',
      'hi': 'कॉन्फ़िगरेशन समस्याएं',
    },
    'teams': {'en': 'Teams', 'ar': 'الفرق', 'ur': 'ٹیمیں', 'hi': 'टीमें'},
    'projects': {
      'en': 'Projects',
      'ar': 'المشاريع',
      'ur': 'منصوبے',
      'hi': 'परियोजनाएं',
    },
    'review_queue': {
      'en': 'Review & approval queue',
      'ar': 'قائمة المراجعة والموافقة',
      'ur': 'جائزہ اور منظوری قطار',
      'hi': 'समीक्षा और अनुमोदन कतार',
    },
    'status_submitted': {
      'en': 'Submitted',
      'ar': 'مقدم',
      'ur': 'جمع شدہ',
      'hi': 'प्रस्तुत',
    },
    'status_under_review': {
      'en': 'Under review',
      'ar': 'قيد المراجعة',
      'ur': 'زیر جائزہ',
      'hi': 'समीक्षाधीन',
    },
    'status_returned_for_correction': {
      'en': 'Returned for correction',
      'ar': 'معاد للتصحيح',
      'ur': 'اصلاح کے لیے واپس',
      'hi': 'सुधार हेतु लौटाया',
    },
    'status_awaiting_final_approval': {
      'en': 'Awaiting final approval',
      'ar': 'بانتظار الموافقة النهائية',
      'ur': 'حتمی منظوری کا منتظر',
      'hi': 'अंतिम अनुमोदन प्रतीक्षित',
    },
    'server_confirmed': {
      'en': 'Server confirmed',
      'ar': 'مؤكد من الخادم',
      'ur': 'سرور سے تصدیق شدہ',
      'hi': 'सर्वर पुष्ट',
    },
    'stale': {
      'en': 'Last confirmed — connection unavailable',
      'ar': 'آخر تأكيد — الاتصال غير متاح',
      'ur': 'آخری تصدیق — کنکشن دستیاب نہیں',
      'hi': 'अंतिम पुष्टि — कनेक्शन अनुपलब्ध',
    },
    'loading': {
      'en': 'Loading protected Workforce overview…',
      'ar': 'جارٍ تحميل نظرة القوى العاملة المحمية…',
      'ur': 'محفوظ افرادی قوت جائزہ لوڈ ہو رہا ہے…',
      'hi': 'सुरक्षित कार्यबल अवलोकन लोड हो रहा है…',
    },
    'empty': {
      'en': 'No authorized Workforce scope is available.',
      'ar': 'لا يوجد نطاق قوى عاملة مصرح به.',
      'ur': 'کوئی مجاز افرادی قوت دائرہ دستیاب نہیں۔',
      'hi': 'कोई अधिकृत कार्यबल दायरा उपलब्ध नहीं है।',
    },
    'denied': {
      'en': 'Workforce overview access is unavailable.',
      'ar': 'الوصول إلى نظرة القوى العاملة غير متاح.',
      'ur': 'افرادی قوت جائزہ تک رسائی دستیاب نہیں۔',
      'hi': 'कार्यबल अवलोकन पहुंच अनुपलब्ध है।',
    },
    'failed': {
      'en': 'The overview could not be confirmed. Retry safely.',
      'ar': 'تعذر تأكيد النظرة العامة. أعد المحاولة بأمان.',
      'ur': 'جائزے کی تصدیق نہیں ہو سکی۔ محفوظ طریقے سے دوبارہ کوشش کریں۔',
      'hi': 'अवलोकन की पुष्टि नहीं हुई। सुरक्षित रूप से पुनः प्रयास करें।',
    },
    'local_as_of': {
      'en': 'Local as of',
      'ar': 'محلي اعتبارًا من',
      'ur': 'مقامی تاریخ',
      'hi': 'स्थानीय तिथि',
    },
    'submitted_by': {
      'en': 'Submitted by',
      'ar': 'مقدم من',
      'ur': 'جمع کرانے والا',
      'hi': 'प्रस्तुतकर्ता',
    },
    'team': {'en': 'Team', 'ar': 'الفريق', 'ur': 'ٹیم', 'hi': 'टीम'},
    'month': {'en': 'Month', 'ar': 'الشهر', 'ur': 'ماہ', 'hi': 'माह'},
    'worker_count': {
      'en': 'Workers',
      'ar': 'العمال',
      'ur': 'ورکرز',
      'hi': 'कर्मचारी',
    },
    'regular_ot': {
      'en': 'Regular / OT',
      'ar': 'عادي / إضافي',
      'ur': 'باقاعدہ / او ٹی',
      'hi': 'नियमित / ओटी',
    },
    'corrections': {
      'en': 'Reviewer corrections',
      'ar': 'تصحيحات المراجع',
      'ur': 'جائزہ کار کی اصلاحات',
      'hi': 'समीक्षक सुधार',
    },
    'missing_supporting_evidence': {
      'en': 'Missing Supporting Evidence',
      'ar': 'أدلة الدعم المفقودة',
      'ur': 'غائب معاون ثبوت',
      'hi': 'अनुपस्थित सहायक साक्ष्य',
    },
    'high_overtime': {
      'en': 'High Overtime',
      'ar': 'عمل إضافي مرتفع',
      'ur': 'زیادہ اوور ٹائم',
      'hi': 'अधिक ओवरटाइम',
    },
    'policy_not_configured': {
      'en': 'Not configured',
      'ar': 'غير مهيأ',
      'ur': 'کنفیگر نہیں',
      'hi': 'कॉन्फ़िगर नहीं',
    },
    'policy_typed_validation_issue': {
      'en': 'Typed validation issue',
      'ar': 'مشكلة تحقق مصنفة',
      'ur': 'درجہ بند توثیقی مسئلہ',
      'hi': 'टाइप किया गया सत्यापन मुद्दा',
    },
    'minutes': {'en': 'min', 'ar': 'دقيقة', 'ur': 'منٹ', 'hi': 'मिनट'},
    'read_only_mobile': {
      'en': 'Read-only summary on this screen size',
      'ar': 'ملخص للقراءة فقط على هذا الحجم',
      'ur': 'اس اسکرین پر صرف پڑھنے کا خلاصہ',
      'hi': 'इस स्क्रीन आकार पर केवल-पढ़ने योग्य सारांश',
    },
  };

  static String text(AppLanguage language, String key) =>
      _copy[key]?[language.code] ?? _copy[key]?['en'] ?? key;
}
