// Generated by tool/generate-notification-catalogue.py. Do not edit.
export const moduleEvents: Record<string, {title: Record<string,string>; body: Record<string,string>; destination: string; urgent: boolean}> = {
  "accounts_claim_ready": {
    "title": {
      "en": "Claim ready for Accounts",
      "ar": "المطالبة جاهزة للحسابات",
      "ur": "اکاؤنٹس کے لیے کلیم تیار",
      "hi": "लेखा के लिए दावा तैयार"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "invoices",
    "urgent": false
  },
  "accounts_claim_returned": {
    "title": {
      "en": "Claim changes required",
      "ar": "مطلوب تعديل المطالبة",
      "ur": "کلیم میں تبدیلی درکار",
      "hi": "दावे में बदलाव आवश्यक"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "invoices",
    "urgent": false
  },
  "accounts_certification_difference": {
    "title": {
      "en": "Certification needs review",
      "ar": "شهادة الدفع تحتاج مراجعة",
      "ur": "سرٹیفیکیشن کا جائزہ درکار",
      "hi": "प्रमाणन की समीक्षा आवश्यक"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "invoices",
    "urgent": false
  },
  "accounts_supplier_evidence_incomplete": {
    "title": {
      "en": "Supplier bill evidence incomplete",
      "ar": "مستندات فاتورة المورد غير مكتملة",
      "ur": "سپلائر بل کے ثبوت نامکمل",
      "hi": "आपूर्तिकर्ता बिल के प्रमाण अधूरे"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "supplier-bills",
    "urgent": false
  },
  "accounts_supplier_bill_ready": {
    "title": {
      "en": "Supplier bill ready for Accounts",
      "ar": "فاتورة المورد جاهزة للحسابات",
      "ur": "سپلائر بل اکاؤنٹس کے لیے تیار",
      "hi": "आपूर्तिकर्ता बिल लेखा के लिए तैयार"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "supplier-bills",
    "urgent": false
  },
  "accounts_invoice_due_soon": {
    "title": {
      "en": "Invoice due soon",
      "ar": "موعد الفاتورة قريب",
      "ur": "انوائس جلد واجب الادا",
      "hi": "चालान जल्द देय"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "invoices",
    "urgent": false
  },
  "accounts_invoice_overdue": {
    "title": {
      "en": "Invoice overdue",
      "ar": "فاتورة متأخرة",
      "ur": "انوائس کی تاریخ گزر گئی",
      "hi": "चालान अतिदेय"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "invoices",
    "urgent": true
  },
  "accounts_pdc_due_soon": {
    "title": {
      "en": "Cheque due soon",
      "ar": "موعد الشيك قريب",
      "ur": "چیک جلد واجب الادا",
      "hi": "चेक जल्द देय"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "receipts-pdc",
    "urgent": false
  },
  "accounts_pdc_overdue": {
    "title": {
      "en": "Cheque overdue",
      "ar": "شيك متأخر",
      "ur": "چیک کی تاریخ گزر گئی",
      "hi": "चेक अतिदेय"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "receipts-pdc",
    "urgent": true
  },
  "workforce_period_submitted": {
    "title": {
      "en": "Timesheet ready for review",
      "ar": "كشف الدوام جاهز للمراجعة",
      "ur": "ٹائم شیٹ جائزے کے لیے تیار",
      "hi": "टाइमशीट समीक्षा के लिए तैयार"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "timesheets",
    "urgent": false
  },
  "workforce_period_returned": {
    "title": {
      "en": "Timesheet changes required",
      "ar": "مطلوب تعديل كشف الدوام",
      "ur": "ٹائم شیٹ میں تبدیلی درکار",
      "hi": "टाइमशीट में बदलाव आवश्यक"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "timesheets",
    "urgent": false
  },
  "workforce_correction_completed": {
    "title": {
      "en": "Timesheet corrected",
      "ar": "تم تصحيح كشف الدوام",
      "ur": "ٹائم شیٹ درست کر دی گئی",
      "hi": "टाइमशीट सुधारी गई"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "timesheets",
    "urgent": false
  },
  "workforce_period_verified": {
    "title": {
      "en": "Timesheet verified",
      "ar": "تم التحقق من كشف الدوام",
      "ur": "ٹائم شیٹ کی تصدیق ہو گئی",
      "hi": "टाइमशीट सत्यापित"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "timesheets",
    "urgent": false
  },
  "workforce_period_approved_locked": {
    "title": {
      "en": "Timesheet approved and locked",
      "ar": "تم اعتماد وإقفال كشف الدوام",
      "ur": "ٹائم شیٹ منظور اور مقفل",
      "hi": "टाइमशीट स्वीकृत और लॉक"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "timesheets",
    "urgent": false
  },
  "workforce_reopen_requested": {
    "title": {
      "en": "Timesheet reopening requested",
      "ar": "طُلب إعادة فتح كشف الدوام",
      "ur": "ٹائم شیٹ دوبارہ کھولنے کی درخواست",
      "hi": "टाइमशीट दोबारा खोलने का अनुरोध"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "timesheets",
    "urgent": false
  },
  "workforce_reopen_approved": {
    "title": {
      "en": "Timesheet reopening approved",
      "ar": "اعتُمد إعادة فتح كشف الدوام",
      "ur": "ٹائم شیٹ دوبارہ کھولنے کی منظوری",
      "hi": "टाइमशीट दोबारा खोलना स्वीकृत"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "timesheets",
    "urgent": false
  },
  "workforce_final_approval_required": {
    "title": {
      "en": "Timesheet final approval required",
      "ar": "مطلوب الاعتماد النهائي لكشف الدوام",
      "ur": "ٹائم شیٹ کی حتمی منظوری درکار",
      "hi": "टाइमशीट की अंतिम स्वीकृति आवश्यक"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "timesheets",
    "urgent": false
  },
  "workforce_daily_attendance_missing": {
    "title": {
      "en": "Daily attendance missing",
      "ar": "الحضور اليومي غير مسجل",
      "ur": "روزانہ حاضری درج نہیں",
      "hi": "दैनिक उपस्थिति अनुपलब्ध"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "attendance",
    "urgent": false
  },
  "workforce_monthly_period_incomplete": {
    "title": {
      "en": "Monthly timesheet incomplete",
      "ar": "كشف الدوام الشهري غير مكتمل",
      "ur": "ماہانہ ٹائم شیٹ نامکمل",
      "hi": "मासिक टाइमशीट अधूरी"
    },
    "body": {
      "en": "Open the workspace to review this update.",
      "ar": "افتح مساحة العمل لمراجعة هذا التحديث.",
      "ur": "اس اپ ڈیٹ کا جائزہ لینے کے لیے ورک اسپیس کھولیں۔",
      "hi": "इस अपडेट की समीक्षा के लिए कार्यक्षेत्र खोलें।"
    },
    "destination": "timesheets",
    "urgent": false
  }
};
